import aiofiles
import dataclasses
import pathlib

from code_specs import FileExtension, MarkerChar, MarkersOverlapError, Validator, comment_string, get_markers


@dataclasses.dataclass(frozen=True)
class PathAndValidator:
  """An immutable container for a DM file path and a validator."""
  dm_path: pathlib.Path
  validator: Validator

  async def validate_fields(self) -> None:
    """Validates fields, conditionally raising ValueError.

    When searching for markers, uses MarkerChar('🍄').

    {{🦔 Doesn't raise if `dm_path` is a valid file with two 🍄 markers.}}
    {{🦔 Raises ValueError if `dm_path` is "foo.py" (lacks the `.dm.` part).}}
    {{🦔 Raises ValueError if `dm_path` is a valid file with no 🍄 markers.}}
    {{🦔 Raises ValueError if `dm_path` contains a repeated 🍄 marker.}}

    We can't use `__post_init__` because we want `async` validation.
    """
    # {{🍄 PathAndValidator validate fields}}

  def file_extension(self) -> FileExtension:
    """Returns the file extension of the `dm_path`.

    {{🦔 For `dm_path` "foo/bar/quux.dm.py", returns "py"}}
    """
    raise NotImplementedError()  # {{🍄 PathAndValidator file extension}}

  def output_path(self) -> pathlib.Path:
    """Returns `dm_path` without the `.dm` part.

    {{🦔 If `dm_path` is "foo/bar/quux.dm.py", returns "foo/bar/quux.py"}}
    """
    raise NotImplementedError()  # {{🍄 PathAndValidator output path}}

  def old_path(self) -> pathlib.Path:
    """Returns the "old" path, where the previous implementation is backed up.

    This is done by replacing the ".dm." part with ".old.".

    When expansion begins, we use these paths to make a copy of previous files
    that we'll overwrite.

    {{🦔 For `dm_path` "foo/bar.dm.py", returns "foo/bar.old.py".}}
    """
    raise NotImplementedError()  # {{🍄 PathAndValidator old path}}

  async def overwrite(self, target: pathlib.Path) -> None:
    """Copies `dm_path`'s contents to `target` (overwriting it).

    The contents of the new file are:

    * A line with the comment:
      "DO NOT EDIT. This file is automatically generated by Duende."
    * The entire (unmodified) contents of `dm_path`.

    {{🦔 The read operation is async}}
    {{🦔 The write operation is async}}
    {{🦔 The output of a call with a normal dm file starts with the "DO NOT EDIT
         code comment}}
    {{🦔 The output of a call with a normal dm file contains a copy (of the dm
         file), starting at line 2 (of the output)}}
    """
    raise NotImplementedError()  # {{🍄 overwrite}}
