# DO NOT EDIT. This file is automatically generated by Duende.
# Suggested validator: MYPYPATH=~/coding-agent/src mypy $DMPATH

import aiofiles
import asyncio
import collections
import dataclasses
import itertools
import logging
import pathlib
import re
import os
import shutil
import subprocess
import tempfile
from typing import Awaitable, Callable, NamedTuple, NewType, Pattern, Sequence

from agent_command import Argument, ArgumentContentType, VariableMap, VariableName, VariableValue
from agent_loop_options import AgentLoopOptions
from agent_workflow_options import AgentWorkflowOptions
from command_registry import CommandRegistry
from done_command import DoneCommand, DoneValuesValidator
from file_access_policy import FileAccessPolicy
from list_files_command import ListFilesCommand
from message import Message, ContentSection
from read_file_command import ReadFileCommand
from search_file_command import SearchFileCommand
from validation import ValidationResult
from write_file_command import WriteFileCommand


async def prepare_initial_message(start_message_content: str,
                                  relevant_files: set[pathlib.Path]) -> Message:
  """Creates the first message for an AgentLoop conversation.

  {{🦔 `relevant_files` are read asynchronously.}}
  {{🦔 The output contains `start_message_content` as its first section.}}
  {{🦔 If `relevant_files` is empty, the output has just one section.}}
  {{🦔 If a relevant file can't be read, raises an exception (or, rather, lets
       the underlying exception bubble up, doesn't catch it).}}
  {{🦔 There is a content section in the start message given to the AgentLoop
       for each entry in `relevant_files`. It starts with a line "File '{path}'
       follows:" (with the corresponding path) and includes the entire contents
       of the file.}}
  """
  # ✨ prepare initial message
  content_sections = [ContentSection(content=start_message_content)]

  for file_path in sorted(relevant_files):
    async with aiofiles.open(file_path, mode='r') as f:
      file_content = await f.read()
    content_sections.append(
        ContentSection(content=f"File '{file_path}' follows:" + "\n" +
                       file_content))

  return Message(role="user", content_sections=content_sections)
  # ✨


async def prepare_command_registry(
    done_command_arguments: list[Argument],
    done_validator_callback: Callable[[VariableMap],
                                      Awaitable[ValidationResult]],
    file_access_policy: FileAccessPolicy) -> CommandRegistry:
  """Creates a command registry suitable for run_agent_loop.

  {{🦔 The command registry given has exactly these agent commands:
       ReadFileCommand(…), ListFilesCommand(…), SearchFileCommand(…),
       done_command}}
  """

  # ✨ prepare command registry
  class CallbackDoneValuesValidator(DoneValuesValidator):

    def __init__(self, callback: Callable[[VariableMap],
                                          Awaitable[ValidationResult]]):
      self._callback = callback

    async def validate(self, inputs: VariableMap) -> ValidationResult:
      return await self._callback(inputs)

  registry = CommandRegistry()
  registry.Register(ReadFileCommand(file_access_policy))
  registry.Register(ListFilesCommand(file_access_policy))
  registry.Register(SearchFileCommand(file_access_policy))
  registry.Register(
      DoneCommand(
          arguments=done_command_arguments,
          values_validator=CallbackDoneValuesValidator(
              done_validator_callback)))
  return registry
  # ✨


async def run_agent_loop(workflow_options: AgentWorkflowOptions,
                         conversation_name: str, start_message: Message,
                         command_registry: CommandRegistry) -> VariableMap:
  """Creates and runs a BaseAgentLoop.

  {{🦔 Returns the `VariableMap` with all the values given to `DoneCommand`.}}
  {{🦔 The conversation started has name `conversation_name`.}}
  {{🦔 `start_message` is given as the initial message.}}

  Returns:
    Output variables given to the final `done` command (extracted from the
    final message in the conversation).
  """
  # ✨ run agent loop
  conversation = workflow_options.conversation_factory.New(
      conversation_name, command_registry)

  # Create new AgentLoopOptions, overriding conversation, start_message, and command_registry
  # from the workflow_options's agent_loop_options.
  agent_loop_options = workflow_options.agent_loop_options._replace(
      conversation=conversation,
      start_message=start_message,
      command_registry=command_registry)

  agent_loop = workflow_options.agent_loop_factory.new(agent_loop_options)

  return await agent_loop.run()
  # ✨
