# DO NOT EDIT. This file is automatically generated by Duende.
import asyncio
from concurrent.futures import ThreadPoolExecutor
import datetime
import dataclasses
import logging
import pathlib
import sqlite3
from typing import Callable, NewType, ParamSpec, TypeVar, cast

from conversation import ConversationId
from swarm_types import AgentName

# MessageId is meant for the IDs of messages in the SQL database. It is NOT
# meant for the IDs of Telegram messages (use TelegramMessageId for those).
MessageId = NewType("MessageId", int)  # Unique ID across the bus.
TelegramChatId = NewType("TelegramChatId", int)
TelegramMessageId = NewType("TelegramMessageId", int)

# Wrapper for the `content` fields in the message bus.
MessageContent = NewType("MessageContent", str)

# Fake agent name reserved to represent the end user.
END_USER_AGENT = AgentName("duende-internal:end-user")


@dataclasses.dataclass(frozen=True)
class Message:
  # The fields map directly to the rows of the `message_bus` SQL table.
  #
  # Paths use `pathlib.Path`.
  # ✨ message fields
  message_id: MessageId
  source_agent: AgentName
  target_agent: AgentName
  local_directory: pathlib.Path | None
  conversation_id: ConversationId | None
  telegram_chat_id: TelegramChatId
  telegram_message_id: TelegramMessageId | None
  telegram_reply_to_id: TelegramMessageId | None
  content: MessageContent
  queued_at: datetime.datetime
  processed_at: datetime.datetime | None
  # ✨


T = TypeVar("T")
P = ParamSpec("P")


class MessageBus:

  def __init__(self, path: pathlib.Path) -> None:
    self._path = path
    self._executor = ThreadPoolExecutor(max_workers=1)
    # _connection is only accessed by threads running in _executor.
    self._connection: sqlite3.Connection | None = None

  async def _run_in_thread(self, func: Callable[P, T], *args: P.args,
                           **kwargs: P.kwargs) -> T:
    loop = asyncio.get_running_loop()
    return await loop.run_in_executor(self._executor,
                                      lambda: func(*args, **kwargs))

  async def _poll_in_thread(self,
                            func: Callable[[], list[Message]]) -> list[Message]:
    """Runs `func` once per second until it returns values."""
    # ✨ poll in thread
    _poll_interval_secs = 1.0

    while True:
      messages = await self._run_in_thread(func)
      if messages:
        logging.info(f'New messages: {len(messages)}')
        return messages
      else:
        await asyncio.sleep(_poll_interval_secs)
    # ✨

  async def open(self) -> None:
    """Connects to the bus, potentially initializing it.

    If the database is empty (or does not exist), creates the expected tables
    (see message_bus.sql for details).

    Passes timeout=20.0 and isolation_level=None when connecting.
    """

    def _open() -> None:
      # ✨ init db
      self._connection = sqlite3.connect(
          str(self._path), timeout=20.0, isolation_level=None)
      self._connection.execute("PRAGMA journal_mode=WAL;")
      self._connection.row_factory = sqlite3.Row
      # Create tables if they don't exist
      sql_schema = """
        CREATE TABLE IF NOT EXISTS message_bus (
            message_id INTEGER PRIMARY KEY AUTOINCREMENT,

            source_agent TEXT NOT NULL,
            target_agent TEXT NOT NULL,

            local_directory TEXT,

            conversation_id INTEGER,

            telegram_chat_id INTEGER NOT NULL,

            telegram_message_id INTEGER,
            telegram_reply_to_id INTEGER,

            content TEXT NOT NULL,

            queued_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            processed_at DATETIME
        );
        """
      self._connection.executescript(sql_schema)
      self._connection.commit()
      # ✨

    await self._run_in_thread(_open)

  async def wait_for_incoming_messages(
      self, agents: list[AgentName]) -> list[Message]:
    """Polls until new incoming messages arrive for the agents listed.

    A new incoming message is one with `processed_at` set to NULL.
    """

    def _load_messages() -> list[Message]:
      """May return empty list."""
      # ✨ load incoming messages
      if not agents:
        return []

      agent_placeholders = ', '.join(['?' for _ in agents])
      query = f"""
          SELECT
              message_id,
              source_agent,
              target_agent,
              local_directory,
              conversation_id,
              telegram_chat_id,
              telegram_message_id,
              telegram_reply_to_id,
              content,
              queued_at,
              processed_at
          FROM message_bus
          WHERE processed_at IS NULL AND target_agent IN ({agent_placeholders})
      """
      if self._connection is None:
        raise ValueError("Database connection is not open.")

      cursor = self._connection.execute(query, tuple(agents))
      new_messages_rows = cursor.fetchall()

      messages = []
      for row in new_messages_rows:
        messages.append(
            Message(
                message_id=MessageId(row['message_id']),
                source_agent=AgentName(row['source_agent']),
                target_agent=AgentName(row['target_agent']),
                local_directory=pathlib.Path(row['local_directory'])
                if row['local_directory'] else None,
                conversation_id=ConversationId(row['conversation_id'])
                if row['conversation_id'] else None,
                telegram_chat_id=TelegramChatId(row['telegram_chat_id']),
                telegram_message_id=TelegramMessageId(
                    row['telegram_message_id'])
                if row['telegram_message_id'] else None,
                telegram_reply_to_id=TelegramMessageId(
                    row['telegram_reply_to_id'])
                if row['telegram_reply_to_id'] else None,
                content=MessageContent(row['content']),
                queued_at=datetime.datetime.fromisoformat(row['queued_at']),
                processed_at=datetime.datetime.fromisoformat(
                    row['processed_at']) if row['processed_at'] else None,
            ))
      return messages
      # ✨

    return await self._poll_in_thread(_load_messages)

  async def wait_for_outgoing_messages(self) -> list[Message]:
    """Polls until new outgoing messages arrive.

    A new outgoing message is one with `telegram_message_id` set to `NULL` and
    `agent` set to the value in `END_USER_AGENT`.
    """

    def _load_messages() -> list[Message]:
      # ✨ load outgoing messages
      if self._connection is None:
        raise ValueError("Database connection is not open.")

      query = """
          SELECT
              message_id,
              source_agent,
              target_agent,
              local_directory,
              conversation_id,
              telegram_chat_id,
              telegram_message_id,
              telegram_reply_to_id,
              content,
              queued_at,
              processed_at
          FROM message_bus
          WHERE telegram_message_id IS NULL AND target_agent = ?
      """
      cursor = self._connection.execute(query, (END_USER_AGENT,))
      new_messages_rows = cursor.fetchall()

      messages = []
      for row in new_messages_rows:
        messages.append(
            Message(
                message_id=MessageId(row['message_id']),
                source_agent=AgentName(row['source_agent']),
                target_agent=AgentName(row['target_agent']),
                local_directory=pathlib.Path(row['local_directory'])
                if row['local_directory'] else None,
                conversation_id=ConversationId(row['conversation_id'])
                if row['conversation_id'] else None,
                telegram_chat_id=TelegramChatId(row['telegram_chat_id']),
                telegram_message_id=TelegramMessageId(
                    row['telegram_message_id'])
                if row['telegram_message_id'] else None,
                telegram_reply_to_id=TelegramMessageId(
                    row['telegram_reply_to_id'])
                if row['telegram_reply_to_id'] else None,
                content=MessageContent(row['content']),
                queued_at=datetime.datetime.fromisoformat(row['queued_at']),
                processed_at=datetime.datetime.fromisoformat(
                    row['processed_at']) if row['processed_at'] else None,
            ))
      return messages
      # ✨

    return await self._poll_in_thread(_load_messages)

  async def set_conversation_id(self, message_id: MessageId,
                                conversation_id: ConversationId) -> None:
    # ✨ set message conversation
    def _set_conversation_id_db_op(msg_id: MessageId,
                                   conv_id: ConversationId) -> None:
      """Synchronous database operation to set the conversation_id."""
      if self._connection is None:
        raise ValueError("Database connection is not open.")

      cursor = self._connection.execute(
          "UPDATE message_bus SET conversation_id = ? WHERE message_id = ? AND conversation_id IS NULL",
          (conv_id, msg_id),
      )
      self._connection.commit()
      if cursor.rowcount == 0:
        # This means either the message_id was not found, or conversation_id was already set.
        # In either case, we consider this an error as per the requirement.
        raise ValueError(
            f"Message with ID {msg_id} not found or conversation_id already set."
        )
      elif cursor.rowcount > 1:
        # This should ideally not happen with a PRIMARY KEY condition.
        raise RuntimeError(
            f"Multiple messages with ID {msg_id} updated, which should not happen."
        )

    await self._run_in_thread(_set_conversation_id_db_op, message_id,
                              conversation_id)
    # ✨

  async def write_new_message(self, message: Message) -> Message:
    """Adds a new message to the database.

    The MessageId will be overwritten (based on database state) and the
    resulting message returned.
    """

    # ✨ write new message
    def _insert_message_and_commit(msg: Message) -> Message:
      """Synchronous database operation to insert a new message."""
      if self._connection is None:
        raise ValueError("Database connection is not open.")

      logging.info(
          'Writing message: source_agent=%s, target_agent=%s, local_directory=%s, conversation_id=%s, telegram_chat_id=%s, telegram_message_id=%s, telegram_reply_to_id=%s, content="%s", queued_at=%s',
          msg.source_agent,
          msg.target_agent,
          msg.local_directory,
          msg.conversation_id,
          msg.telegram_chat_id,
          msg.telegram_message_id,
          msg.telegram_reply_to_id,
          msg.content,
          msg.queued_at,
      )
      cursor = self._connection.execute(
          """
            INSERT INTO message_bus (
                source_agent,
                target_agent,
                local_directory,
                conversation_id,
                telegram_chat_id,
                telegram_message_id,
                telegram_reply_to_id,
                content,
                queued_at,
                processed_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
          (
              msg.source_agent,
              msg.target_agent,
              str(msg.local_directory) if msg.local_directory else None,
              msg.conversation_id if msg.conversation_id else None,
              msg.telegram_chat_id,
              msg.telegram_message_id if msg.telegram_message_id else None,
              msg.telegram_reply_to_id if msg.telegram_reply_to_id else None,
              msg.content,
              msg.queued_at,
              None,  # processed_at is NULL for new messages
          ),
      )
      self._connection.commit()
      new_id = cursor.lastrowid
      if new_id is None:
        raise RuntimeError(
            "Failed to retrieve the ID of the newly inserted message.")
      logging.info('Wrote message with ID: %s', new_id)
      return dataclasses.replace(msg, message_id=MessageId(new_id))

    return await self._run_in_thread(
        _insert_message_and_commit,
        message,
    )
    # ✨

  async def mark_as_processed(self, message_id: MessageId) -> None:
    """Sets processed_at to the current time."""

    # ✨ set processed at
    def _mark_as_processed_db_op(msg_id: MessageId) -> None:
      """Synchronous database operation to set the processed_at timestamp."""
      if self._connection is None:
        raise ValueError("Database connection is not open.")

      cursor = self._connection.execute(
          "UPDATE message_bus SET processed_at = CURRENT_TIMESTAMP WHERE message_id = ? AND processed_at IS NULL",
          (msg_id,),
      )
      self._connection.commit()
      if cursor.rowcount == 0:
        raise ValueError(
            f"Message with ID {msg_id} not found or already processed.")
      elif cursor.rowcount > 1:
        raise RuntimeError(
            f"Multiple messages with ID {msg_id} updated, which should not happen."
        )

    await self._run_in_thread(_mark_as_processed_db_op, message_id)
    # ✨

  async def set_telegram_message_id(
      self, message_id: MessageId,
      telegram_message_id: TelegramMessageId) -> None:
    """Updates the telegram_message_id of a given row.

    It is an error to try to update a message_id where the telegram_message_id
    already has a value (we use a conditional update and validate that exactly
    1 row was updated).
    """

    # ✨ set telegram message id
    def _set_telegram_message_id_db_op(msg_id: MessageId,
                                       tg_msg_id: TelegramMessageId) -> None:
      """Synchronous database operation to set the telegram_message_id."""
      if self._connection is None:
        raise ValueError("Database connection is not open.")

      cursor = self._connection.execute(
          "UPDATE message_bus SET telegram_message_id = ? WHERE message_id = ? AND telegram_message_id IS NULL",
          (tg_msg_id, msg_id),
      )
      self._connection.commit()
      if cursor.rowcount == 0:
        # This means either the message_id was not found, or telegram_message_id was already set.
        raise ValueError(
            f"Message with ID {msg_id} not found or telegram_message_id already set."
        )
      elif cursor.rowcount > 1:
        # This should ideally not happen with a PRIMARY KEY condition.
        raise RuntimeError(
            f"Multiple messages with ID {msg_id} updated, which should not happen."
        )

    await self._run_in_thread(_set_telegram_message_id_db_op, message_id,
                              telegram_message_id)
    # ✨

  async def read_message(self, message_id: MessageId) -> Message:
    """Returns a message from the database or raises ValueError."""

    # ✨ read message
    def _read_message_db_op(msg_id: MessageId) -> Message:
      """Synchronous database operation to read a message by its ID."""
      if self._connection is None:
        raise ValueError("Database connection is not open.")

      query = """
          SELECT
              message_id,
              source_agent,
              target_agent,
              local_directory,
              conversation_id,
              telegram_chat_id,
              telegram_message_id,
              telegram_reply_to_id,
              content,
              queued_at,
              processed_at
          FROM message_bus
          WHERE message_id = ?
      """
      logging.info('Reading message with ID: %s', msg_id)

      cursor = self._connection.execute(query, (msg_id,))
      row = cursor.fetchone()

      if row is None:
        raise ValueError(f"Message with ID {msg_id} not found.")

      message = Message(
          message_id=MessageId(row['message_id']),
          source_agent=AgentName(row['source_agent']),
          target_agent=AgentName(row['target_agent']),
          local_directory=pathlib.Path(row['local_directory'])
          if row['local_directory'] else None,
          conversation_id=ConversationId(row['conversation_id'])
          if row['conversation_id'] else None,
          telegram_chat_id=TelegramChatId(row['telegram_chat_id']),
          telegram_message_id=TelegramMessageId(row['telegram_message_id'])
          if row['telegram_message_id'] else None,
          telegram_reply_to_id=TelegramMessageId(row['telegram_reply_to_id'])
          if row['telegram_reply_to_id'] else None,
          content=MessageContent(row['content']),
          queued_at=datetime.datetime.fromisoformat(row['queued_at']),
          processed_at=datetime.datetime.fromisoformat(row['processed_at'])
          if row['processed_at'] else None,
      )
      logging.info('Read message with ID: %s', msg_id)
      return message

    return await self._run_in_thread(_read_message_db_op, message_id)
    # ✨

  async def find_message_by_telegram_id(
      self, telegram_chat_id: TelegramChatId,
      telegram_message_id: TelegramMessageId) -> Message:
    """Returns a message from the database or raises ValueError."""

    # ✨ find message by telegram id
    def _find_message_by_telegram_id_db_op(
        telegram_chat_id: TelegramChatId,
        telegram_message_id: TelegramMessageId) -> Message:
      """Synchronous database operation to find a message by Telegram IDs."""
      if self._connection is None:
        raise ValueError("Database connection is not open.")

      query = """
          SELECT
              message_id,
              source_agent,
              target_agent,
              local_directory,
              conversation_id,
              telegram_chat_id,
              telegram_message_id,
              telegram_reply_to_id,
              content,
              queued_at,
              processed_at
          FROM message_bus
          WHERE telegram_chat_id = ? AND telegram_message_id = ?
      """
      logging.info(
          'Finding message by telegram_chat_id=%s, telegram_message_id=%s',
          telegram_chat_id, telegram_message_id)

      cursor = self._connection.execute(query,
                                        (telegram_chat_id, telegram_message_id))
      row = cursor.fetchone()

      if row is None:
        raise ValueError(
            f"Message with telegram_chat_id={telegram_chat_id} and telegram_message_id={telegram_message_id} not found."
        )

      message = Message(
          message_id=MessageId(row['message_id']),
          source_agent=AgentName(row['source_agent']),
          target_agent=AgentName(row['target_agent']),
          local_directory=pathlib.Path(row['local_directory'])
          if row['local_directory'] else None,
          conversation_id=ConversationId(row['conversation_id'])
          if row['conversation_id'] else None,
          telegram_chat_id=TelegramChatId(row['telegram_chat_id']),
          telegram_message_id=TelegramMessageId(row['telegram_message_id'])
          if row['telegram_message_id'] else None,
          telegram_reply_to_id=TelegramMessageId(row['telegram_reply_to_id'])
          if row['telegram_reply_to_id'] else None,
          content=MessageContent(row['content']),
          queued_at=datetime.datetime.fromisoformat(row['queued_at']),
          processed_at=datetime.datetime.fromisoformat(row['processed_at'])
          if row['processed_at'] else None,
      )
      logging.info('Found message with ID: %s', message.message_id)
      return message

    return await self._run_in_thread(
        _find_message_by_telegram_id_db_op,
        telegram_chat_id,
        telegram_message_id,
    )
    # ✨
