# DO NOT EDIT. This file is automatically generated by Duende.
import asyncio
import dataclasses
import pathlib
import sqlite3
from typing import NewType

from swarm_types import AgentName

SenderName = AgentName | None
RecipientName = AgentName | None
MessageBus = NewType('MessageBus', sqlite3.Connection)
MessageId = NewType('MessageId', int)  # Unique ID across the bus.
SessionId = NewType('SessionId', str)  # A UUID.


@dataclasses.dataclass(frozen=True)
class Message:
  # Fields for the rows in the `message_bus` table (see message_bus.sql).
  id: MessageId
  sender: SenderName
  recipient: RecipientName
  session_id: SessionId | None
  body: str


async def open_bus(path: pathlib.Path) -> MessageBus:
  """Connects to the bus, potentially initializing it.

  If the database is empty (or does not exist), creates the expected tables
  (see message_bus.sql for details).
  """
  # ✨ open bus
  db = await asyncio.to_thread(sqlite3.connect, path)
  db.row_factory = sqlite3.Row
  # Create tables if they don't exist
  sql_schema = """
  CREATE TABLE IF NOT EXISTS messages (
      -- Unique identifier for each message
      id INTEGER PRIMARY KEY AUTOINCREMENT,

      -- Core Mailing List Fields
      sender TEXT NOT NULL,
      recipient TEXT NOT NULL,
      sent_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      body TEXT NOT NULL,

      -- Queue Management
      -- Status can only be 'new' or 'seen'
      status TEXT NOT NULL DEFAULT 'new'
          CHECK (status IN ('new', 'seen')),

      -- Metadata (Optional)
      reply_to TEXT,
      session_id TEXT,

      -- Message Classification
      -- Type can only be 'info', 'final', or 'question'
      message_type TEXT NOT NULL
          CHECK (message_type IN ('info', 'final', 'question'))
  );

  -- Index for the server to find "new" messages quickly
  CREATE INDEX IF NOT EXISTS idx_pending_messages ON messages(status) WHERE status = 'new';
  """
  await asyncio.to_thread(db.executescript, sql_schema)
  await asyncio.to_thread(db.commit)
  return MessageBus(db)
  # ✨


async def wait_for_new_messages(
    db: MessageBus, recipients: list[RecipientName]) -> list[Message]:
  """Polls db until new messages arrive for the recipients listed.

  A new message is one with status set to 'new'.

  Initially polls after one second, growing polling frequency exponentially up
  to one minute.
  """
  # ✨ wait for new messages
  _poll_interval_secs = 1.0
  _max_poll_interval_secs = 60.0

  while True:
    if not recipients:
      return []

    recipient_placeholders = ', '.join(['?' for _ in recipients])
    query = f"""
        SELECT id, sender, recipient, session_id, body
        FROM messages
        WHERE status = 'new' AND recipient IN ({recipient_placeholders})
    """
    cursor = await asyncio.to_thread(db.execute, query, tuple(recipients))
    new_messages_rows = await asyncio.to_thread(cursor.fetchall)

    if new_messages_rows:
      messages = []
      for row in new_messages_rows:
        messages.append(
            Message(
                id=MessageId(row['id']),
                sender=AgentName(row['sender']),
                recipient=AgentName(row['recipient']),
                session_id=row['session_id'],
                body=row['body'],
            )
        )
      return messages
    else:
      await asyncio.sleep(_poll_interval_secs)
      _poll_interval_secs = min(_poll_interval_secs * 2, _max_poll_interval_secs)
  # ✨


async def mark_message_as_seen(db: MessageBus, message_id: MessageId) -> None:
  """Updates the `status` field in self._messages_db to `seen`."""
  # ✨ mark message as seen
  await asyncio.to_thread(db.execute, "UPDATE messages SET status = 'seen' WHERE id = ?", (message_id,))
  await asyncio.to_thread(db.commit)
  # ✨


async def write_new_message(db: MessageBus, message: Message) -> MessageId:
  """Adds a new message to the database.

  The MessageId will be overwritten (based on database state) and returned.
  """
  # ✨ write new message
  cursor = await asyncio.to_thread(
      db.execute,
      """
      INSERT INTO messages (sender, recipient, session_id, body, status, message_type)
      VALUES (?, ?, ?, ?, ?, ?)
      """,
      (
          message.sender,
          message.recipient,
          message.session_id,
          message.body,
          'new',  # Default status
          'info', # Default message_type
      ),
  )
  await asyncio.to_thread(db.commit)

  new_message_id = cursor.lastrowid
  if new_message_id is None:
    raise RuntimeError("Failed to retrieve the ID of the newly inserted message.")

  return MessageId(new_message_id)
  # ✨