# DO NOT EDIT. This file is automatically generated by Duende.
import aiofiles
import dataclasses
import json
import pathlib
from typing import NewType

TelegramId = NewType("TelegramId", int)

from swarm_types import AgentName


@dataclasses.dataclass(frozen=True)
class AgentIdentityConfig:
  # Unique name of this agent
  name: AgentName

  capability: list[str]

  prompt_path: pathlib.Path

  file_access_policy_regex: str


@dataclasses.dataclass(frozen=True)
class SwarmConfig:
  agents: dict[AgentName, AgentIdentityConfig]
  # Path to the SQLite DB containing the messages queue.
  message_bus_path: pathlib.Path

  telegram_token: str | None

  telegram_consumer: AgentName | None

  telegram_authorized_users: list[TelegramId]


async def load_config(path: pathlib.Path) -> SwarmConfig:
  """Loads the configuration from JSON file in `path`.

  If `telegram_token` is set:

  * `telegram_authorized_users` must not be empty.
  * `telegram_consumer` must be set to a key in `agents`.

  If `telegram_authorized_users` or `telegram_consumer` is set, `telegram_token`
  must also be set.
  """
  # ✨ load config
  async with aiofiles.open(
      path, mode="r") as f:
    content = await f.read()
  data = json.loads(content)

  agents = {}
  for agent_name, agent_data in data["agents"].items():
    agents[AgentName(agent_name)] = AgentIdentityConfig(
        name=AgentName(agent_name),
        capability=agent_data["capability"],
        prompt_path=pathlib.Path(agent_data["prompt_path"]),
        file_access_policy_regex=agent_data["file_access_policy_regex"],
    )

  telegram_token = data.get("telegram_token")
  telegram_consumer_name = data.get("telegram_consumer")
  telegram_authorized_users_raw = data.get("telegram_authorized_users", [])
  telegram_authorized_users = [TelegramId(uid) for uid in telegram_authorized_users_raw]

  telegram_consumer: AgentName | None = None
  if telegram_consumer_name:
    telegram_consumer = AgentName(telegram_consumer_name)
    if telegram_consumer not in agents:
      raise ValueError(f"telegram_consumer '{telegram_consumer_name}' is not defined in agents.")

  if telegram_token:
    if not telegram_authorized_users:
      raise ValueError("If 'telegram_token' is set, 'telegram_authorized_users' must not be empty.")
    if not telegram_consumer:
      raise ValueError("If 'telegram_token' is set, 'telegram_consumer' must be set.")
  else: # telegram_token is None
    if telegram_authorized_users:
      raise ValueError("If 'telegram_authorized_users' is set, 'telegram_token' must also be set.")
    if telegram_consumer:
      raise ValueError("If 'telegram_consumer' is set, 'telegram_token' must also be set.")

  return SwarmConfig(
      agents=agents,
      message_bus_path=pathlib.Path(data["message_bus_path"]),
      telegram_token=telegram_token,
      telegram_consumer=telegram_consumer,
      telegram_authorized_users=telegram_authorized_users,
  )
  # ✨