# DO NOT EDIT. This file is automatically generated by Duende.
import datetime

from agent_command import AgentCommand, CommandInput, CommandOutput, CommandSyntax, Argument, ArgumentContentType, REASON_VARIABLE, VariableMap, VariableName, VariableValueInt
from conversation import ConversationId
from file_access_policy import FileAccessPolicy
from message_bus import Message as BusMessage, END_USER_AGENT, MessageBus, MessageContent, MessageId, TelegramChatId, TelegramMessageId
from message_queue import AgentMessageQueue
from swarm_types import AgentName

_TARGET_AGENT_ARGUMENT = Argument(
    name=VariableName("target_agent"),
    arg_type=ArgumentContentType.STRING,
    description="The name of the agent that should consume the message.",
    required=True)

_CONTENT_ARGUMENT = Argument(
    name=VariableName("content"),
    arg_type=ArgumentContentType.STRING,
    description="The content to send to the user.",
    required=True)


class DisplayInfoCommand(AgentCommand):

  def __init__(self, message_bus: MessageBus, conversation_id: ConversationId,
               telegram_chat_id: TelegramChatId,
               telegram_reply_to_id: TelegramMessageId,
               source_agent: AgentName) -> None:
    # ✨ display info store private fields
    self._message_bus = message_bus
    self._conversation_id = conversation_id
    self._telegram_chat_id = telegram_chat_id
    self._telegram_reply_to_id = telegram_reply_to_id
    self._source_agent = source_agent
    # ✨

  def Name(self) -> str:
    return self.Syntax().name

  def Syntax(self) -> CommandSyntax:
    return CommandSyntax(
        name="display_info",
        description="Displays information to the user.",
        arguments=[REASON_VARIABLE, _CONTENT_ARGUMENT])

  async def run(self, inputs: VariableMap) -> CommandOutput:
    """Call write_new_message with a new message.

    {{🦔 target_agent is set to the value in `END_USER_AGENT`.}}
    """
    # ✨ display info run
    content_val = inputs[VariableName("content")]
    content = str(content_val)
    message = BusMessage(
        message_id=MessageId(0),  # Will be overwritten by the message bus.
        source_agent=self._source_agent,
        target_agent=END_USER_AGENT,
        conversation_id=self._conversation_id,
        telegram_chat_id=self._telegram_chat_id,
        telegram_message_id=None, # This is an outgoing message from agent to user, no Telegram ID yet
        telegram_reply_to_id=self._telegram_reply_to_id,
        content=MessageContent(content),
        queued_at=datetime.datetime.now(),
        processed_at=None,
    )
    written_message = await self._message_bus.write_new_message(message)
    return CommandOutput(
        command_name=self.Name(),
        output=f"Message sent with ID: {written_message.message_id}",
        errors="",
        summary=f"Displayed info to user: {content[:50]}...",
    )
    # ✨


class PublishMessageCommand(AgentCommand):

  def __init__(self, message_bus: MessageBus, telegram_chat_id: TelegramChatId,
               telegram_reply_to_id: TelegramMessageId,
               source_agent: AgentName) -> None:
    # ✨ publish message store private fields
    self._message_bus = message_bus
    self._telegram_chat_id = telegram_chat_id
    self._telegram_reply_to_id = telegram_reply_to_id
    self._source_agent = source_agent
    # ✨

  def Name(self) -> str:
    return self.Syntax().name

  def Syntax(self) -> CommandSyntax:
    return CommandSyntax(
        name="publish_message",
        description="Publishes a new message into the message bus. "
        "The message will be consumed by an agent.",
        arguments=[REASON_VARIABLE, _TARGET_AGENT_ARGUMENT, _CONTENT_ARGUMENT])

  async def run(self, inputs: VariableMap) -> CommandOutput:
    """Call write_new_message with a new message.

    {{🦔 The message's target_agent is always set.}}
    """
    # ✨ publish message run
    content_val = inputs[VariableName("content")]
    content = str(content_val)
    target_agent_val = inputs[VariableName("target_agent")]
    target_agent = AgentName(str(target_agent_val))

    message = BusMessage(
        message_id=MessageId(0),  # Will be overwritten by the message bus.
        source_agent=self._source_agent,
        target_agent=target_agent,
        conversation_id=None, # This command is for publishing messages between agents, not for direct user conversations.
        telegram_chat_id=self._telegram_chat_id,
        telegram_message_id=None, # This is an internal message, not a Telegram message yet.
        telegram_reply_to_id=self._telegram_reply_to_id,
        content=MessageContent(content),
        queued_at=datetime.datetime.now(),
        processed_at=None,
    )
    written_message = await self._message_bus.write_new_message(message)
    return CommandOutput(
        command_name=self.Name(),
        output=f"Message published to {target_agent} with ID: {written_message.message_id}",
        errors="",
        summary=f"Published message to {target_agent}: {content[:50]}...",
    )
    # ✨


class AskUserCommand(AgentCommand):

  def __init__(self, message_bus: MessageBus, queue: AgentMessageQueue,
               conversation_id: ConversationId,
               telegram_chat_id: TelegramChatId,
               telegram_reply_to_id: TelegramMessageId,
               source_agent: AgentName) -> None:
    # ✨ ask user store private fields
    self._message_bus = message_bus
    self._queue = queue
    self._conversation_id = conversation_id
    self._telegram_chat_id = telegram_chat_id
    self._telegram_reply_to_id = telegram_reply_to_id
    self._source_agent = source_agent
    # ✨

  def Name(self) -> str:
    return self.Syntax().name

  def Syntax(self) -> CommandSyntax:
    return CommandSyntax(
        name="ask_user",
        description="Sends a message to the user and waits for a response.",
        arguments=[
            REASON_VARIABLE,
            Argument(
                name=VariableName("question"),
                arg_type=ArgumentContentType.STRING,
                description="The content of the question to send to the user.",
                required=True),
        ])

  async def run(self, inputs: VariableMap) -> CommandOutput:
    """Waits until self._queue has messages and returns them.

    {{🦔 The CommandOutput.output is set to a str containing all the messages
         read from the queue.}}
    """
    # ✨ ask user run
    question_val = inputs[VariableName("question")]
    question = str(question_val)

    # Send the question to the user
    message = BusMessage(
        message_id=MessageId(0),  # Will be overwritten by the message bus.
        source_agent=self._source_agent,
        target_agent=END_USER_AGENT,
        conversation_id=self._conversation_id,
        telegram_chat_id=self._telegram_chat_id,
        telegram_message_id=None, # This is an outgoing message from agent to user, no Telegram ID yet
        telegram_reply_to_id=self._telegram_reply_to_id,
        content=MessageContent(question),
        queued_at=datetime.datetime.now(),
        processed_at=None,
    )
    await self._message_bus.write_new_message(message)

    # Wait for the user's response
    user_responses = await self._queue.read()
    response_content = "\n".join(user_responses)

    return CommandOutput(
        command_name=self.Name(),
        output=response_content,
        errors="",
        summary=f"Asked user: {question[:50]}... Received response: {response_content[:50]}...",
    )
    # ✨


class DelegateRequestCommand(AgentCommand):

  def __init__(self, message_bus: MessageBus, telegram_chat_id: TelegramChatId,
               telegram_reply_to_id: TelegramMessageId, source_agent: AgentName,
               user_request: MessageContent) -> None:
    # ✨ delegate request store private fields
    self._message_bus = message_bus
    self._telegram_chat_id = telegram_chat_id
    self._telegram_reply_to_id = telegram_reply_to_id
    self._source_agent = source_agent
    self._user_request = user_request
    # ✨

  def Name(self) -> str:
    return self.Syntax().name

  def Syntax(self) -> CommandSyntax:
    return CommandSyntax(
        name="delegate_request",
        description="Forwards the user request to another agent and terminates the session.",
        arguments=[REASON_VARIABLE, _TARGET_AGENT_ARGUMENT])

  async def run(self, inputs: VariableMap) -> CommandOutput:
    """Call write_new_message with a new message with self._user_request.

    {{🦔 The message's `target_agent` is always set.}}
    {{🦔 The returned value has `task_done = True`.}}
    """
    # ✨ delegate request run
    target_agent_val = inputs[VariableName("target_agent")]
    target_agent = AgentName(str(target_agent_val))

    message = BusMessage(
        message_id=MessageId(0),  # Will be overwritten by the message bus.
        source_agent=self._source_agent,
        target_agent=target_agent,
        conversation_id=None,  # This command is for delegating requests between agents.
        telegram_chat_id=self._telegram_chat_id,
        telegram_message_id=None,  # This is an internal message, not a Telegram message yet.
        telegram_reply_to_id=self._telegram_reply_to_id,
        content=self._user_request,
        queued_at=datetime.datetime.now(),
        processed_at=None,
    )
    written_message = await self._message_bus.write_new_message(message)
    return CommandOutput(
        command_name=self.Name(),
        output=f"User request delegated to {target_agent} with ID: {written_message.message_id}",
        errors="",
        summary=f"Delegated user request to {target_agent}.",
        task_done=True,
    )
    # ✨