# DO NOT EDIT. This file is automatically generated by Duende.
import aiofiles
import dataclasses
import json
import pathlib

from swarm_types import AgentName


@dataclasses.dataclass(frozen=True)
class AgentIdentityConfig:
  # Unique name of this agent
  name: AgentName

  capability: list[str]

  prompt_path: pathlib.Path

  file_access_policy_regex: str


@dataclasses.dataclass(frozen=True)
class SwarmConfig:
  agents: dict[AgentName, AgentIdentityConfig]
  # Path to the SQLite DB containing the messages queue.
  message_bus_path: pathlib.Path

  telegram_token: str | None


async def load_config(path: pathlib.Path) -> SwarmConfig:
  """Loads the configuration from JSON file in `path`."""
  # ✨ load config
  async with aiofiles.open(
      path, mode="r") as f:
    content = await f.read()
  data = json.loads(content)

  agents = {}
  for agent_name, agent_data in data["agents"].items():
    agents[AgentName(agent_name)] = AgentIdentityConfig(
        name=AgentName(agent_name),
        capability=agent_data["capability"],
        prompt_path=pathlib.Path(agent_data["prompt_path"]),
        file_access_policy_regex=agent_data["file_access_policy_regex"],
    )
  return SwarmConfig(
      agents=agents,
      message_bus_path=pathlib.Path(data["message_bus_path"]),
      telegram_token=data.get("telegram_token"),
  )
  # ✨
