# DO NOT EDIT. This file is automatically generated by Duende.
import aiofiles
import asyncio
import dataclasses
import datetime
import json
import pathlib
import sqlite3
from typing import NewType
import uuid

from agent_loop_options import BaseAgentLoop
from agent_workflow import AgentWorkflow, AgentWorkflowFactory
from agent_workflow_options import AgentWorkflowOptions
from command_registry import CommandRegistry
from confirmation import ConfirmationManager, ConfirmationState
from conversation import ConversationId, Conversation
from done_command import DoneCommand
from file_access_policy import create_file_access_policy, FileAccessPolicyConfig
from list_files_command import ListFilesCommand
from message import ContentSection, Message
import message_bus
from message_bus import Message as BusMessage, MessageBus, TelegramChatId, TelegramMessageId
from message_queue import AgentMessageQueue
from shell_command_command import ShellCommandCommand
from swarm_commands import AskUserCommand, DelegateRequestConfig, DelegateRequestCommand, DisplayInfoCommand, PublishMessageCommand
from swarm_config import AgentIdentityConfig, SwarmConfig, load_config
from swarm_types import AgentName
from search_file_command import SearchFileCommand
from read_file_command import ReadFileCommand
from write_file_command import WriteFileCommand


class SwarmConfirmationManager(ConfirmationManager):

  def __init__(self, message_bus: MessageBus, agent_name: AgentName,
               delegate: ConfirmationManager) -> None:
    self._message_bus = message_bus
    self._agent_name = agent_name
    self._delegate = delegate

  async def RequireConfirmation(self, conversation_id: ConversationId,
                                message: str) -> str | None:
    dummy_id = message_bus.MessageId(0)
    # TODO: Implement here.
    return await self._delegate.RequireConfirmation(conversation_id, message)

  def provide_confirmation(self, conversation_id: ConversationId,
                           confirmation: str) -> None:
    return self._delegate.provide_confirmation(conversation_id, confirmation)


@dataclasses.dataclass
class AgentSession:
  conversation: Conversation
  loop: BaseAgentLoop
  message_queue: AgentMessageQueue


class SwarmWorkflow(AgentWorkflow):

  def __init__(self, options: AgentWorkflowOptions) -> None:
    self._options = options
    self._background_tasks: list[asyncio.Task[None]] = []
    self._sessions: dict[ConversationId, AgentSession] = {}

  async def run(self) -> None:
    self._config = await load_config(
        self._options.config_path or pathlib.Path('swarm/config.json'))
    self._message_bus = MessageBus(self._config.message_bus_path)
    await self._message_bus.open()
    while True:
      for message in await self._message_bus.wait_for_incoming_messages(
          list(self._config.agents)):
        await self._process_message(message)

  async def _process_message(self, message: BusMessage) -> None:
    """Receives a new incoming message.

    Sets the `process_at` cell to the current time.

    * If `message.source_agent` is NOT the value in END_USER_AGENT: calls
      `_start_agent_loop`.

    * Otherwise, if the `message.message_reply_to_id is None`: calls
      `_start_agent_loop`.

    * Otherwise, if the replied-to message can be found in the bus and the
      replied-to message has a `conversation_id` found in `_sessions`: adds the
      content of the message to the session's `message_queue`.

    * Otherwise: writes an outgoing message informing the user that the session
      no longer exists.
    """
    # ✨ process message
    await self._message_bus.mark_as_processed(message.message_id)

    if message.source_agent != message_bus.END_USER_AGENT:
      # If the message is from another agent, always start a new agent loop.
      await self._start_agent_loop(message)
    elif message.telegram_reply_to_id is None:
      # If the message is from the end user and is not a reply, start a new agent loop.
      await self._start_agent_loop(message)
    else:
      # The message is from the end user and is a reply.
      # Try to find the original message that the user is replying to.
      replied_to_bus_message: BusMessage | None = None
      try:
        replied_to_bus_message = await self._message_bus.find_message_by_telegram_id(
            message.telegram_chat_id, message.telegram_reply_to_id)
      except ValueError:
        # The replied-to message was not found in the bus.
        # This implies the session might be gone or never existed in this bus.
        pass

      if replied_to_bus_message and replied_to_bus_message.conversation_id in self._sessions:
        # If the replied-to message has a conversation_id and that session exists,
        # add the new message content to the session's message queue.
        session = self._sessions[replied_to_bus_message.conversation_id]
        await session.message_queue.push(message.content)
      else:
        # If the session no longer exists or the replied-to message was not found,
        # inform the user that the session no longer exists.
        outgoing_message = BusMessage(
            message_id=message_bus.MessageId(0),
            source_agent=message.target_agent,
            target_agent=AgentName(message_bus.END_USER_AGENT),
            local_directory=None,  # Added local_directory
            conversation_id=None,
            telegram_chat_id=message.telegram_chat_id,
            telegram_message_id=None,
            telegram_reply_to_id=message.telegram_message_id,
            content=message_bus.MessageContent(
                "This conversation session no longer exists. Please start a new conversation."
            ),
            queued_at=datetime.datetime.now(datetime.timezone.utc),
            processed_at=None,
        )
        await self._message_bus.write_new_message(outgoing_message)
    # ✨

  async def _start_agent_loop(self, message: BusMessage) -> None:
    """Starts a new agent loop.

    Calls `MessageBus.set_conversation_id` to write the new conversation id.
    """
    assert message.target_agent
    telegram_id = message.telegram_message_id or message.telegram_reply_to_id
    assert telegram_id
    agent_message_queue = AgentMessageQueue()
    command_registry = CommandRegistry()
    conversation = self._options.conversation_factory.New(
        f"{message.target_agent}: {message.content[:50]}", command_registry)
    self._init_command_registry(conversation.GetId(), telegram_id, message,
                                self._config.agents[message.target_agent],
                                agent_message_queue, command_registry)
    confirmation_manager = SwarmConfirmationManager(
        self._message_bus, message.target_agent, self._options
        .agent_loop_options.confirmation_state.confirmation_manager)
    agent_loop_options = self._options.agent_loop_options._replace(
        conversation=conversation,
        start_message=await self._new_start_message(message),
        command_registry=command_registry,
        file_access_policy=create_file_access_policy(self._config.agents[
            message.target_agent].command_registry.file_access_policy or
                                                     FileAccessPolicyConfig()),
        confirmation_state=ConfirmationState(confirmation_manager, 30))
    # ✨ create and start agent loop
    agent_loop = self._options.agent_loop_factory.new(agent_loop_options)
    session = AgentSession(
        conversation=conversation,
        loop=agent_loop,
        message_queue=agent_message_queue,
    )
    self._sessions[conversation.GetId()] = session

    await self._message_bus.set_conversation_id(message.message_id,
                                                conversation.GetId())

    async def _run_agent_loop_task(loop: BaseAgentLoop) -> None:
      await loop.run()

    self._background_tasks.append(
        asyncio.create_task(_run_agent_loop_task(agent_loop)))
    # ✨

  async def _new_start_message(self, message: BusMessage) -> Message:
    """Returns a new Message: agent's prompt + message's body.

    Loads the prompt from the agent's config's prompt_path and appends the body
    of the message to it.
    """
    assert message.target_agent
    head = self._config.agents[message.target_agent].prompt_content
    tail = "<user_request>" + message.content + "</user_request>"
    # ✨ new start message
    assert message.target_agent
    head = self._config.agents[message.target_agent].prompt_content
    tail = "<user_request>" + message.content + "</user_request>"
    return Message(
        role='user',
        content_sections=[
            ContentSection(content=head),
            ContentSection(content=tail)
        ])
    # ✨

  def _init_command_registry(self, conversation_id: ConversationId,
                             telegram_reply_to_id: TelegramMessageId,
                             message: BusMessage, config: AgentIdentityConfig,
                             queue: AgentMessageQueue,
                             command_registry: CommandRegistry) -> None:
    """Initializes a valid registry for a specific agent identity.

    {{🦔 The registry contains ReadFileCommand, ListFilesCommand,
         SearchFileCommand, DoneCommand (with no arguments),
         DisplayInfoCommand, PublishMessageCommand and AskUserCommand.}}
    {{🦔 If `config.command_registry.allow_shell', the registry contains
         `ShellCommandCommand`.}}
    {{🦔 If `config.command_registry.delegate_request.allow_list' exists and
         is non-empty, the registry contains DelegateRequestCommand.}}
    {{🦔 If `config.command_registry.writes', the registry contains
         `WriteFileCommand`.}}
    {{🦔 The file access policy is based on config.file_access_policy_regex.}}
    """
    # TODO: Figure out how to honor
    # config.command_registry.writes.file_access_policy. With the current
    # implementation of WriteFileCommand, it isn't feasible.

    # ✨ init command registry
    file_access_policy_config = config.command_registry.file_access_policy or FileAccessPolicyConfig(
    )
    file_access_policy = create_file_access_policy(file_access_policy_config)

    command_registry.Register(DoneCommand([]))
    command_registry.Register(ReadFileCommand(self._options.agent_loop_options.cwd))
    command_registry.Register(ListFilesCommand(file_access_policy))
    command_registry.Register(SearchFileCommand(file_access_policy))
    command_registry.Register(
        DisplayInfoCommand(self._message_bus, conversation_id,
                           message.telegram_chat_id, telegram_reply_to_id,
                           message.target_agent))
    command_registry.Register(
        PublishMessageCommand(self._message_bus, message.telegram_chat_id,
                              telegram_reply_to_id, message.target_agent))
    command_registry.Register(
        AskUserCommand(self._message_bus, queue, conversation_id,
                       message.telegram_chat_id, telegram_reply_to_id,
                       message.target_agent))

    if config.command_registry.allow_shell:
      command_registry.Register(ShellCommandCommand())

    if config.command_registry.writes:
      command_registry.Register(
          WriteFileCommand(self._options.agent_loop_options.validation_manager,
                           self._options.selection_manager, None))

    if (config.command_registry.delegate_request and
        config.command_registry.delegate_request.allow_list):
      command_registry.Register(
          DelegateRequestCommand(
              config.command_registry.delegate_request,
              self._message_bus,
              message.telegram_chat_id,
              telegram_reply_to_id,
              message.target_agent,
              message.content,
          ))
    # ✨


class SwarmWorkflowFactory(AgentWorkflowFactory):

  def name(self) -> str:
    return "swarm"

  async def new(self, agent_workflow_options: AgentWorkflowOptions,
                args: dict[str, str]) -> AgentWorkflow:
    return SwarmWorkflow(agent_workflow_options)