# DO NOT EDIT. This file is automatically generated by Duende.
import datetime

from agent_command import AgentCommand, CommandInput, CommandOutput, CommandSyntax, Argument, ArgumentContentType, REASON_VARIABLE, VariableMap, VariableName, VariableValueInt
from conversation import ConversationId
from file_access_policy import FileAccessPolicy
from message_bus import Message as BusMessage, END_USER_AGENT, MessageBus, MessageId, TelegramChatId, TelegramMessageId
from message_queue import AgentMessageQueue
from swarm_types import AgentName


class DisplayInfoCommand(AgentCommand):

  def __init__(self, message_bus: MessageBus, conversation_id: ConversationId,
               telegram_chat_id: TelegramChatId,
               telegram_reply_to_id: TelegramMessageId,
               source_agent: AgentName) -> None:
    # ✨ display info store private fields
    self._message_bus = message_bus
    self._conversation_id = conversation_id
    self._telegram_chat_id = telegram_chat_id
    self._telegram_reply_to_id = telegram_reply_to_id
    self._source_agent = source_agent
    # ✨

  def Name(self) -> str:
    return self.Syntax().name

  @classmethod
  def Syntax(self) -> CommandSyntax:
    return CommandSyntax(
        name="display_info",
        description="Displays information to the user.",
        arguments=[
            REASON_VARIABLE,
            Argument(
                name=VariableName("content"),
                arg_type=ArgumentContentType.STRING,
                description="The content to send to the user.",
                required=True),
        ])

  async def run(self, inputs: VariableMap) -> CommandOutput:
    """Call write_new_message with a new message.

    {{🦔 target_agent is set to the value in `END_USER_AGENT`.}}
    """
    # ✨ display info run
    message = BusMessage(
        id=MessageId(0),  # Will be overwritten by write_new_message
        source_agent=self._source_agent,
        target_agent=AgentName(END_USER_AGENT),
        conversation_id=self._conversation_id,
        telegram_chat_id=self._telegram_chat_id,
        telegram_message_id=None,
        telegram_reply_to_id=self._telegram_reply_to_id,
        content=str(inputs[VariableName("content")]),
        queued_at=datetime.datetime.now(),
        processed_at=None,
    )
    await self._message_bus.write_new_message(message)
    return CommandOutput(
        command_name=self.Name(),
        output="Message sent.",
        errors="",
        summary="",
        task_done=False,
    )
    # ✨


class PublishMessageCommand(AgentCommand):

  def __init__(self, message_bus: MessageBus, conversation_id: ConversationId,
               telegram_chat_id: TelegramChatId,
               telegram_reply_to_id: TelegramMessageId,
               source_agent: AgentName) -> None:
    # ✨ publish message store private fields
    self._message_bus = message_bus
    self._conversation_id = conversation_id
    self._telegram_chat_id = telegram_chat_id
    self._telegram_reply_to_id = telegram_reply_to_id
    self._source_agent = source_agent
    # ✨

  def Name(self) -> str:
    return self.Syntax().name

  @classmethod
  def Syntax(self) -> CommandSyntax:
    return CommandSyntax(
        name="publish_message",
        description="Publishes a new message into the message bus. "
        "The message will be consumed by an agent.",
        arguments=[
            REASON_VARIABLE,
            Argument(
                name=VariableName("content"),
                arg_type=ArgumentContentType.STRING,
                description="The content of the message to publish.",
                required=True),
            Argument(
                name=VariableName("target_agent"),
                arg_type=ArgumentContentType.STRING,
                description="The name of the agent that should consume the message."
            )
        ])

  async def run(self, inputs: VariableMap) -> CommandOutput:
    """Call write_new_message with a new message.

    {{🦔 The message's recipient is always set.}}
    """
    # ✨ publish message run
    message = BusMessage(
        id=MessageId(0),  # Will be overwritten by write_new_message
        source_agent=self._source_agent,
        target_agent=AgentName(str(inputs[VariableName("target_agent")])),
        conversation_id=self._conversation_id,
        telegram_chat_id=self._telegram_chat_id,
        telegram_message_id=None,
        telegram_reply_to_id=self._telegram_reply_to_id,
        content=str(inputs[VariableName("content")]),
        queued_at=datetime.datetime.now(),
        processed_at=None,
    )
    await self._message_bus.write_new_message(message)
    return CommandOutput(
        command_name=self.Name(),
        output=f"Message published to {inputs[VariableName('target_agent')]}.",
        errors="",
        summary="",
        task_done=False,
    )
    # ✨


class AskUserCommand(AgentCommand):

  def __init__(self, message_bus: MessageBus, queue: AgentMessageQueue,
               conversation_id: ConversationId,
               telegram_chat_id: TelegramChatId,
               telegram_reply_to_id: TelegramMessageId,
               source_agent: AgentName) -> None:
    # ✨ ask user store private fields
    self._message_bus = message_bus
    self._queue = queue
    self._conversation_id = conversation_id
    self._telegram_chat_id = telegram_chat_id
    self._telegram_reply_to_id = telegram_reply_to_id
    self._source_agent = source_agent
    # ✨

  def Name(self) -> str:
    return self.Syntax().name

  @classmethod
  def Syntax(self) -> CommandSyntax:
    return CommandSyntax(
        name="ask_user",
        description="Sends a message to the user and waits for a response.",
        arguments=[
            REASON_VARIABLE,
            Argument(
                name=VariableName("question"),
                arg_type=ArgumentContentType.STRING,
                description="The content of the question to send to the user.",
                required=True),
        ])

  async def run(self, inputs: VariableMap) -> CommandOutput:
    """Waits until self._queue has messages and returns them.

    {{🦔 The CommandOutput.output is set to a str containing all the messages
         read from the queue.}}
    """
    # ✨ ask user run
    message = BusMessage(
        id=MessageId(0),  # Will be overwritten by write_new_message
        source_agent=self._source_agent,
        target_agent=AgentName(END_USER_AGENT),
        conversation_id=self._conversation_id,
        telegram_chat_id=self._telegram_chat_id,
        telegram_message_id=None,
        telegram_reply_to_id=self._telegram_reply_to_id,
        content=str(inputs[VariableName("question")]),
        queued_at=datetime.datetime.now(),
        processed_at=None,
    )
    await self._message_bus.write_new_message(message)
    user_messages = await self._queue.read()
    output_content = "\n".join(user_messages)
    return CommandOutput(
        command_name=self.Name(),
        output=output_content,
        errors="",
        summary="",
        task_done=False,
    )
    # ✨