# DO NOT EDIT. This file is automatically generated by Duende.
import asyncio
import datetime
import logging
import pathlib
from telegram import Update
from telegram.ext import Application, CommandHandler, MessageHandler, filters, ContextTypes

import message_bus as mb
from swarm_config import load_config, SwarmConfig
from swarm_types import AgentName

logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    level=logging.INFO)


class Handler:

  def __init__(self, config: SwarmConfig, message_bus: mb.MessageBus) -> None:
    assert config.telegram
    self._config = config
    self._message_bus = message_bus

  async def start(self, update: Update,
                  context: ContextTypes.DEFAULT_TYPE) -> None:
    assert update.message
    await update.message.reply_text("I'm awake!")

  async def echo(self, update: Update,
                 context: ContextTypes.DEFAULT_TYPE) -> None:
    """Receives a message from Telegram and inserts it to the message bus.

    If the update is a response to a previous message, looks up the previous
    message in the message bus. If the previous message is found, the new row
    will set `target_agent` to `original_message.source_agent` and propagate
    `conversation_id`.

    `source_agent` is set to the value in `END_USER_AGENT`.

    A response is sent to the chat and logged: f"Message received ({id=})"
    """
    assert update.effective_chat  # for telegram_chat_id.
    # ✨ write message to bus and respond
    assert update.message
    assert self._config.telegram  # Ensure telegram config is not None
    telegram_chat_id = mb.TelegramChatId(update.effective_chat.id)
    content = update.message.text or ""  # Ensure content is a string
    telegram_message_id = mb.TelegramMessageId(update.message.message_id)

    telegram_reply_to_id: mb.TelegramMessageId | None = None
    if update.message.reply_to_message:
      telegram_reply_to_id = mb.TelegramMessageId(
          update.message.reply_to_message.message_id)

    target_agent = self._config.telegram.consumer_agent
    conversation_id = None

    if telegram_reply_to_id:
      try:
        original_message = await self._message_bus.find_message_by_telegram_id(
            telegram_chat_id, telegram_reply_to_id)
        target_agent = original_message.source_agent
        conversation_id = original_message.conversation_id
      except ValueError:
        logging.warning(
            f"Replied-to message with Telegram ID {telegram_reply_to_id} "
            f"in chat {telegram_chat_id} not found in message bus. "
            "Proceeding with default target_agent and no conversation_id.")

    message_to_bus = mb.Message(
        message_id=mb.MessageId(0),  # Will be overwritten by write_new_message
        source_agent=AgentName(mb.END_USER_AGENT),
        target_agent=target_agent,
        conversation_id=conversation_id,
        telegram_chat_id=telegram_chat_id,
        telegram_message_id=telegram_message_id,
        telegram_reply_to_id=telegram_reply_to_id,
        content=mb.MessageContent(content),
        queued_at=datetime.datetime.now(datetime.timezone.utc),
        processed_at=None,
        local_directory=None,
    )

    written_message = await self._message_bus.write_new_message(message_to_bus)

    response_text = f"Message received (id={written_message.message_id})"
    await update.message.reply_text(response_text)
    logging.info(response_text)
    # ✨

  async def _send_outgoing_messages(self) -> None:
    """Calls wait_for_outgoing_messages and dispatches messages to the user.

    For each message received, calls `self._app.bot.send_message` and
    `set_telegram_message_id` (based on resulting outgoing message).

    {{🦔 The content of the outgoing messages starts with the source agent.}}
    """
    # ✨ read new outgoing messages
    while True:
      logging.info("Waiting for outgoing messages...")
      outgoing_messages = await self._message_bus.wait_for_outgoing_messages()

      for message in outgoing_messages:
        # Prepend the source agent to the message content as per the requirement.
        full_content = f"{message.source_agent}: {message.content}"
        logging.info("Sending message to telegram_chat_id=%s, content=\"%s\"",
                     message.telegram_chat_id, full_content)
        # Using self._app.bot.send_message to dispatch the message.
        # reply_to_message_id is used if message.telegram_reply_to_id is set.
        try:
          sent_message = await self._app.bot.send_message(
              chat_id=message.telegram_chat_id,
              text=full_content,
              reply_to_message_id=message.telegram_reply_to_id)
          await self._message_bus.set_telegram_message_id(
              message_id=message.message_id,
              telegram_message_id=mb.TelegramMessageId(sent_message.message_id))
          logging.info(
              "Message sent and telegram_message_id updated for bus message_id=%s, telegram_message_id=%s",
              message.message_id, sent_message.message_id)
        except Exception as e:
          logging.error("Failed to send message_id=%s to Telegram: %s",
                        message.message_id, e)
    # ✨

  async def run(self) -> None:
    await self._message_bus.open()
    assert self._config.telegram
    assert self._config.telegram.token
    self._app = Application.builder().token(self._config.telegram.token).build()
    self._app.add_handler(
        CommandHandler(
            "start",
            self.start,
            filters=filters.User(self._config.telegram.authorized_users)))
    self._app.add_handler(
        MessageHandler(
            filters.TEXT & ~filters.COMMAND
            & filters.User(self._config.telegram.authorized_users), self.echo))

    asyncio.create_task(self._send_outgoing_messages())

    async with self._app:
      await self._app.initialize()
      await self._app.start()
      assert self._app.updater
      await self._app.updater.start_polling()
      print("Bot is polling... Press Ctrl+C to stop.")
      while True:
        await asyncio.sleep(1)


async def main() -> None:
  config = await load_config(pathlib.Path('swarm/config.json'))
  assert config.telegram
  await Handler(config, mb.MessageBus(config.message_bus_path)).run()


if __name__ == '__main__':
  asyncio.run(main())