# DO NOT EDIT. This file is automatically generated by Duende.
import unittest
import asyncio
import os
import tempfile
import shutil
import aiofiles
import pathlib
import re

from file_access_policy import CurrentDirectoryFileAccessPolicy, RegexFileAccessPolicy
from agent_command import CommandOutput
from list_files import list_all_files


class ListAllFilesTest(unittest.IsolatedAsyncioTestCase):
  """Contains a good set of tests for `list_all_files`."""

  def setUp(self):
    self.original_cwd = os.getcwd()
    self.temp_dir = pathlib.Path(tempfile.mkdtemp())
    os.chdir(self.temp_dir)
    self._setUpInitialStructure()

  def _setUpInitialStructure(self):
    """Sets up the following structure (with empty files):

    animals/mammals: dog.txt, cat.txt, fox.txt
    animals/birds: tucan.jpg, condor.txt
    fruits: banana.md, orange.md
    """
    # ✨ create directory structure
    os.makedirs("animals/mammals")
    os.makedirs("animals/birds")
    os.makedirs("fruits")

    # Create files
    for f in [
        "animals/mammals/dog.txt", "animals/mammals/cat.txt",
        "animals/mammals/fox.txt", "animals/birds/tucan.jpg",
        "animals/birds/condor.txt", "fruits/banana.md", "fruits/orange.md"
    ]:
      with open(f, "w") as fp:
        fp.write("")
    # ✨

  def tearDown(self):
    os.chdir(self.original_cwd)
    shutil.rmtree(self.temp_dir)

  async def testRoot(self):
    """Root search (".") finds expected number of files."""
    # ✨ root
    file_access_policy = CurrentDirectoryFileAccessPolicy()
    file_paths = [f async for f in list_all_files(".", file_access_policy)]
    self.assertEqual(len(file_paths), 7)
    # ✨

  async def testRootFormat(self):
    """The output of root search (".") is as expected.

    Expected format: "fruits/banana.md"."""
    # ✨ expected output root
    file_access_policy = CurrentDirectoryFileAccessPolicy()
    file_paths = sorted([f async for f in list_all_files(".", file_access_policy)])  # Sort for consistent order

    self.assertIn("fruits/banana.md", file_paths)
    self.assertIn("animals/mammals/dog.txt", file_paths)
    self.assertIn("animals/birds/tucan.jpg", file_paths)

    # Validate format for a few entries
    for path in file_paths:
      self.assertTrue(re.match(r"^[a-zA-Z0-9_]+/.*\.[a-zA-Z0-9_]+$", path))
    # ✨

  async def testEmpty(self):
    """No files are returned for a search in an empty directory."""
    # ✨ empty
    os.makedirs("empty_dir")
    file_access_policy = CurrentDirectoryFileAccessPolicy()
    file_paths = [f async for f in list_all_files("empty_dir", file_access_policy)]
    self.assertEqual(len(file_paths), 0)
    # ✨

  async def testFlat(self):
    """Search in a flat directory returns expected number of outputs."""
    # ✨ flat
    file_access_policy = CurrentDirectoryFileAccessPolicy()
    file_paths = [f async for f in list_all_files("fruits", file_access_policy)]
    self.assertEqual(len(file_paths), 2)
    # ✨

  async def testFlatFormat(self):
    """Search in flat directory returns entries with expected format.

    Expected format: "animals/birds/condor.txt"."""
    # ✨ flat format
    file_access_policy = CurrentDirectoryFileAccessPolicy()
    file_paths = sorted([f async for f in list_all_files("animals/birds", file_access_policy)])
    self.assertListEqual(
        file_paths, ["animals/birds/condor.txt", "animals/birds/tucan.jpg"])
    # ✨

  async def testNestedDirs(self):
    """Search in animals outputs five entries in the expected format."""
    # ✨ nested dirs
    file_access_policy = CurrentDirectoryFileAccessPolicy()
    file_paths = [f async for f in list_all_files("animals", file_access_policy)]
    self.assertEqual(len(file_paths), 5)

    expected_files = [
        "animals/birds/condor.txt",
        "animals/birds/tucan.jpg",
        "animals/mammals/cat.txt",
        "animals/mammals/dog.txt",
        "animals/mammals/fox.txt",
    ]
    self.assertListEqual(sorted(file_paths), expected_files)
    # ✨

  async def testFileAccessPolicy(self):
    """Search in root directory only outputs entries allowed by access policy.

    Creates a regex file access policy matching two files and validates that
    the outputs are exactly as expected."""
    # ✨ file access policy
    file_access_policy = RegexFileAccessPolicy(r"^(animals/mammals/dog.txt|fruits/banana.md)$")
    file_paths = [f async for f in list_all_files(".", file_access_policy)]
    self.assertListEqual(
        sorted(file_paths), [
            "animals/mammals/dog.txt",
            "fruits/banana.md",
        ])
    # ✨

  async def testFileAccessPolicyNoMatch(self):
    """Runs successfully if file access policy doesn't match anything."""
    # ✨ file access policy no match
    file_access_policy = RegexFileAccessPolicy(r"(non_existent_file.txt)$")
    file_paths = [f async for f in list_all_files(".", file_access_policy)]
    self.assertListEqual(file_paths, [])
    # ✨

if __name__ == '__main__':
  unittest.main()
