# DO NOT EDIT. This file is automatically generated by Duende.
# DM validator:
#
# mypy $DMPATH && $PYTHON -m pytest $DMPATH
#
# See src/test-constraints.md for constraints that apply to these tests.

import aiofiles
import asyncio
import pathlib
import re
import tempfile
import unittest

from agent_command import Argument, ArgumentContentType, VariableMap, VariableName, VariableValueStr
from agent_loop_options import AgentLoopOptions, BaseAgentLoopFactory
from agent_workflow_options import AgentWorkflowOptions
from code_specs import FileExtension, MarkerChar, comment_string, get_markers
from code_specs_agent import prepare_command_registry, prepare_initial_message, run_agent_loop
from code_specs_validator import Validator
from code_specs_path_and_validator import PathAndValidator
from command_registry import CommandRegistry
from conversation import ConversationFactory, Conversation
from done_command import DoneCommand
from file_access_policy import FileAccessPolicy
from list_files_command import ListFilesCommand
from message import ContentSection, Message
from read_file_command import ReadFileCommand
from search_file_command import SearchFileCommand
from selection_manager import SelectionManager
from test_utils import FakeFileAccessPolicy, FakeConfirmationState, FakeConfirmationManager, FakeSelectionManager
from validation import ValidationResult


class TestPathAndValidator(unittest.IsolatedAsyncioTestCase):

  async def test_validate_fields_doesnt_raise_if_dm_path_is_a_valid_file_with_two_markers(
      self) -> None:
    # ✨ PathAndValidator validate_fields Doesn't raise if `dm_path` is a valid file with two 🍄 markers.
    with tempfile.TemporaryDirectory() as tmpdir:
      temp_path = pathlib.Path(tmpdir) / "test.dm.py"
      async with aiofiles.open(temp_path, "w") as f:
        marker_start = '{{' + '{'  # Construct '{{' to avoid agent parsing
        marker_end = '}' + '}'  # Construct '}}' to avoid agent parsing
        mushroom = '\U0001f344'  # Use unicode escape for 🍄

        file_content = ("# This is a test file\n"
                        f"# {marker_start}{mushroom} MarkerOne{marker_end}\n"
                        "# Some code here\n"
                        f"# {marker_start}{mushroom} MarkerTwo{marker_end}\n")
        await f.write(file_content)

      dummy_validator = Validator(command="true # $DMPATH")
      path_and_validator = PathAndValidator(temp_path, dummy_validator)

      # This should not raise any exception
      await path_and_validator.validate_fields()
    # ✨

  async def test_validate_fields_raises_value_error_if_dm_path_is_foo_py_lacks_the_dm_part(
      self) -> None:
    # ✨ PathAndValidator validate_fields Raises ValueError if `dm_path` is "foo.py" (lacks the `.dm.` part).
    with tempfile.TemporaryDirectory() as tmpdir:
      temp_path = pathlib.Path(tmpdir) / "foo.py"
      # No need to create the file, as the error is expected before file access.
      dummy_validator = Validator(command="true # $DMPATH")
      path_and_validator = PathAndValidator(temp_path, dummy_validator)

      # Escape special regex characters in the path and '.dm.' string
      expected_error_regex = f"`dm_path` \('{re.escape(str(temp_path))}'\) must contain '\.dm\.'."
      with self.assertRaisesRegex(ValueError, expected_error_regex):
        await path_and_validator.validate_fields()
    # ✨

  async def test_validate_fields_raises_value_error_if_dm_path_is_a_valid_file_with_no_markers(
      self) -> None:
    # ✨ PathAndValidator validate_fields Raises ValueError if `dm_path` is a valid file with no 🍄 markers.
    with tempfile.TemporaryDirectory() as tmpdir:
      temp_path = pathlib.Path(tmpdir) / "test_no_markers.dm.py"
      async with aiofiles.open(temp_path, "w") as f:
        file_content = ("# This is a test file with no markers\n"
                        "print('Hello, world!')\n")
        await f.write(file_content)

      dummy_validator = Validator(command="true # $DMPATH")
      path_and_validator = PathAndValidator(temp_path, dummy_validator)

      # The expected error message for no markers found.
      # We check for a substring to avoid complex regex escaping issues with f-strings.
      expected_error_message_substring = f"No 🍄 markers found in '{str(temp_path)}'."
      with self.assertRaisesRegex(ValueError,
                                  re.escape(expected_error_message_substring)):
        await path_and_validator.validate_fields()
    # ✨

  async def test_validate_fields_raises_value_error_if_dm_path_contains_a_repeated_marker(
      self) -> None:
    # ✨ PathAndValidator validate_fields Raises ValueError if `dm_path` contains a repeated 🍄 marker.
    with tempfile.TemporaryDirectory() as tmpdir:
      temp_path = pathlib.Path(tmpdir) / "repeated_marker.dm.py"
      async with aiofiles.open(temp_path, "w") as f:
        marker_start = '{' + '{'  # Construct '{{' to avoid agent parsing
        marker_end = '}' + '}'  # Construct '}}' to avoid agent parsing
        mushroom = '🍄'  # Use unicode escape for 🍄

        repeated_marker_name = "RepeatedMarker"
        file_content = (
            "# This is a test file with a repeated marker\n"
            f"# {marker_start}{mushroom} {repeated_marker_name}{marker_end}\n"
            "# Some code here\n"
            f"# {marker_start}{mushroom} {repeated_marker_name}{marker_end}\n"
            "# More code\n")
        await f.write(file_content)

      dummy_validator = Validator(command="true # $DMPATH")
      path_and_validator = PathAndValidator(temp_path, dummy_validator)

      # The expected error message for a repeated marker.
      expected_error_message_substring = (
          f"Repeated {mushroom} marker '{repeated_marker_name}' found in "
          f"'{str(temp_path)}' at lines: 1, 3. Each marker name must be unique."
      )
      with self.assertRaisesRegex(ValueError,
                                  re.escape(expected_error_message_substring)):
        await path_and_validator.validate_fields()
    # ✨

  def test_file_extension_for_dm_path_foobarquux_dm_py_returns_py(self) -> None:
    # ✨ PathAndValidator file_extension For `dm_path` "foo/bar/quux.dm.py", returns "py"
    # Create a dummy dm_path
    dm_path = pathlib.Path("foo/bar/quux.dm.py")
    # Create a dummy validator (its command doesn't matter for this test)
    dummy_validator = Validator(command="true # $DMPATH")

    path_and_validator = PathAndValidator(dm_path, dummy_validator)
    result = path_and_validator.file_extension()

    self.assertEqual(result, FileExtension("py"))
    # ✨

  def test_output_path_if_dm_path_is_foobarquux_dm_py_returns_foobarquux_py(
      self) -> None:
    # ✨ PathAndValidator output_path If `dm_path` is "foo/bar/quux.dm.py", returns "foo/bar/quux.py"
    # Create a dummy dm_path
    dm_path = pathlib.Path("foo/bar/quux.dm.py")
    # Create a dummy validator (its command doesn't matter for this test)
    dummy_validator = Validator(command="true # $DMPATH")

    path_and_validator = PathAndValidator(dm_path, dummy_validator)
    result = path_and_validator.output_path()

    self.assertEqual(result, pathlib.Path("foo/bar/quux.py"))
    # ✨

  def test_old_path_for_dm_path_foobar_dm_py_returns_foobar_old_py(
      self) -> None:
    # ✨ PathAndValidator old_path For `dm_path` "foo/bar.dm.py", returns "foo/bar.old.py".
    # Create a dummy dm_path
    dm_path = pathlib.Path("foo/bar.dm.py")
    # Create a dummy validator (its command doesn't matter for this test)
    dummy_validator = Validator(command="true # $DMPATH")

    path_and_validator = PathAndValidator(dm_path, dummy_validator)
    result = path_and_validator.old_path()

    self.assertEqual(result, pathlib.Path("foo/bar.old.py"))
    # ✨

  async def test_overwrite_the_read_operation_is_async(self) -> None:
    # ✨ PathAndValidator overwrite The read operation is async
    import unittest.mock as mock

    with tempfile.TemporaryDirectory() as tmpdir:
      dm_file_path = pathlib.Path(tmpdir) / "test_dm_file.dm.py"
      target_file_path = pathlib.Path(tmpdir) / "test_target_file.py"

      # The content that the mocked aiofiles.open (read mode) will return.
      mocked_dm_content = "# Mocked DM Content\nAnother line\n"

      # Determine the expected auto-generated comment for the target file.
      file_extension = FileExtension(
          "py")  # Assuming .py for this test scenario
      auto_gen_comment = comment_string(
          file_extension,
          "DO NOT EDIT. This file is automatically generated by Duende.")

      expected_write_content = f"{auto_gen_comment}\n{mocked_dm_content}"

      dummy_validator = Validator(command="true # $DMPATH")
      path_and_validator = PathAndValidator(dm_file_path, dummy_validator)

      with mock.patch('aiofiles.open') as mock_aiofiles_open:
        # --- Mocks for the read operation ---
        # This is 'f' in 'async with aiofiles.open(..., mode='r') as f:'
        mock_read_file_handle = mock.AsyncMock()
        mock_read_file_handle.read.return_value = mocked_dm_content

        # This IS the async context manager for reading
        mock_read_async_context_manager = mock.AsyncMock()
        mock_read_async_context_manager.__aenter__.return_value = mock_read_file_handle
        mock_read_async_context_manager.__aexit__.return_value = None

        # --- Mocks for the write operation ---
        # This is 'f' in 'async with aiofiles.open(..., mode='w') as f:'
        mock_write_file_handle = mock.AsyncMock()

        # This IS the async context manager for writing
        mock_write_async_context_manager = mock.AsyncMock()
        mock_write_async_context_manager.__aenter__.return_value = mock_write_file_handle
        mock_write_async_context_manager.__aexit__.return_value = None

        def mock_open_side_effect(file_path, mode, **kwargs):
          if mode == 'r':
            return mock_read_async_context_manager
          elif mode == 'w':
            return mock_write_async_context_manager
          else:
            # Fallback for other modes if any, though not expected here
            return mock.AsyncMock()

        mock_aiofiles_open.side_effect = mock_open_side_effect

        # Call the method under test
        await path_and_validator.overwrite(target_file_path)

        # Assertions for the read operation:
        # Verify aiofiles.open was called to read the dm_path
        mock_aiofiles_open.assert_any_call(dm_file_path, mode='r')
        # Verify that the 'read' method on the file handle was awaited once
        mock_read_file_handle.read.assert_awaited_once()

        # Assertions for the write operation:
        # Verify aiofiles.open was called to write to the target_file_path
        mock_aiofiles_open.assert_any_call(target_file_path, mode='w')
        # Verify that the 'write' method on the file handle was awaited once
        mock_write_file_handle.write.assert_awaited_once_with(
            expected_write_content)

        # Ensure that the target file does not exist because the filesystem operations
        # are fully mocked. This confirms the mocks are effectively in place.
        self.assertFalse(target_file_path.exists())
    # ✨

  async def test_overwrite_the_write_operation_is_async(self) -> None:
    # ✨ PathAndValidator overwrite The write operation is async
    import unittest.mock as mock

    with tempfile.TemporaryDirectory() as tmpdir:
      dm_file_path = pathlib.Path(tmpdir) / "test_dm_file.dm.py"
      target_file_path = pathlib.Path(tmpdir) / "test_target_file.py"

      # The content that the mocked aiofiles.open (read mode) will return.
      mocked_dm_content = "This is some dummy DM content.\nLine 2 of DM.\n"

      # Determine the expected auto-generated comment for the target file.
      file_extension = FileExtension(
          "py")  # Assuming .py for this test scenario
      auto_gen_comment = comment_string(
          file_extension,
          "DO NOT EDIT. This file is automatically generated by Duende.")

      expected_write_content = f"{auto_gen_comment}\n{mocked_dm_content}"

      dummy_validator = Validator(command="true # $DMPATH")
      path_and_validator = PathAndValidator(dm_file_path, dummy_validator)

      with mock.patch('aiofiles.open') as mock_aiofiles_open:
        # --- Mocks for the read operation ---
        # This is 'f' in 'async with aiofiles.open(..., mode='r') as f:'
        mock_read_file_handle = mock.AsyncMock()
        mock_read_file_handle.read.return_value = mocked_dm_content

        # This IS the async context manager for reading
        mock_read_async_context_manager = mock.AsyncMock()
        mock_read_async_context_manager.__aenter__.return_value = mock_read_file_handle
        mock_read_async_context_manager.__aexit__.return_value = None

        # --- Mocks for the write operation ---
        # This is 'f' in 'async with aiofiles.open(..., mode='w') as f:'
        mock_write_file_handle = mock.AsyncMock()

        # This IS the async context manager for writing
        mock_write_async_context_manager = mock.AsyncMock()
        mock_write_async_context_manager.__aenter__.return_value = mock_write_file_handle
        mock_write_async_context_manager.__aexit__.return_value = None

        def mock_open_side_effect(file_path, mode, **kwargs):
          if mode == 'r':
            return mock_read_async_context_manager
          elif mode == 'w':
            return mock_write_async_context_manager
          else:
            # Fallback for other modes if any, though not expected here
            return mock.AsyncMock()

        mock_aiofiles_open.side_effect = mock_open_side_effect

        # Call the method under test
        await path_and_validator.overwrite(target_file_path)

        # Assertions for the write operation:
        # Verify aiofiles.open was called to write to the target_file_path
        mock_aiofiles_open.assert_any_call(target_file_path, mode='w')
        # Verify that the 'write' method on the file handle was awaited once
        mock_write_file_handle.write.assert_awaited_once_with(
            expected_write_content)

        # Ensure that the target file does not exist because the filesystem operations
        # are fully mocked. This confirms the mocks are effectively in place.
        self.assertFalse(target_file_path.exists())
    # ✨

  async def test_overwrite_the_output_of_a_call_with_a_normal_dm_file_starts_with_the_do_not_edit_code_comment(
      self) -> None:
    # ✨ PathAndValidator overwrite The output of a call with a normal dm file starts with the "DO NOT EDIT code comment
    with tempfile.TemporaryDirectory() as tmpdir:
      dm_file_path = pathlib.Path(tmpdir) / "test.dm.py"
      target_file_path = pathlib.Path(tmpdir) / "test.py"

      dm_content = "print('Hello from DM file!')"
      async with aiofiles.open(dm_file_path, "w") as f:
        await f.write(dm_content)

      dummy_validator = Validator(command="true # $DMPATH")
      path_and_validator = PathAndValidator(dm_file_path, dummy_validator)

      await path_and_validator.overwrite(target_file_path)

      async with aiofiles.open(target_file_path, "r") as f:
        actual_content = await f.read()

      expected_comment = comment_string(
          FileExtension("py"),
          "DO NOT EDIT. This file is automatically generated by Duende.")

      # The actual_content will have the comment plus a newline, then the dm_content.
      # We check if it starts with the expected comment.
      self.assertTrue(actual_content.startswith(f"{expected_comment}\n"))
      self.assertEqual(actual_content.splitlines()[0], expected_comment)
    # ✨

  async def test_overwrite_the_output_of_a_call_with_a_normal_dm_file_contains_a_copy_of_the_dm_file_starting_at_line_2_of_the_output(
      self) -> None:
    # ✨ PathAndValidator overwrite The output of a call with a normal dm file contains a copy (of the dm file), starting at line 2 (of the output)
    with tempfile.TemporaryDirectory() as tmpdir:
      dm_file_path = pathlib.Path(tmpdir) / "test.dm.py"
      target_file_path = pathlib.Path(tmpdir) / "test.py"

      original_dm_content = "line 1 of dm file\nline 2 of dm file\nline 3 of dm file"
      async with aiofiles.open(dm_file_path, "w") as f:
        await f.write(original_dm_content)

      dummy_validator = Validator(command="true # $DMPATH")
      path_and_validator = PathAndValidator(dm_file_path, dummy_validator)

      await path_and_validator.overwrite(target_file_path)

      async with aiofiles.open(target_file_path, "r") as f:
        actual_content = await f.read()

      actual_lines = actual_content.splitlines()

      # The first line is the auto-generated comment, so the dm_content should start from the second line.
      # Join the original_dm_content lines with newline characters to compare correctly.
      self.assertEqual("\n".join(actual_lines[1:]), original_dm_content)
    # ✨


if __name__ == '__main__':
  unittest.main()
