# DO NOT EDIT. This file is automatically generated by Duende.
import asyncio
import logging
import os
import pathlib
import shutil
import tempfile
import unittest

from code_specs_workflow import MarkerImplementation, MarkerName, _get_comment_char
from file_access_policy import CurrentDirectoryFileAccessPolicy


class MarkerImplementationTest(unittest.IsolatedAsyncioTestCase):
  """Contains tests for `MarkerImplementation`."""

  def setUp(self) -> None:
    self.original_cwd = os.getcwd()
    self.temp_dir = pathlib.Path(tempfile.mkdtemp())
    os.chdir(self.temp_dir)

  def tearDown(self) -> None:
    os.chdir(self.original_cwd)
    shutil.rmtree(self.temp_dir)

  def writeTempFile(self, contents: str) -> pathlib.Path:
    # ✨ write temp file
    temp_file_path = self.temp_dir / "test_file.txt"
    temp_file_path.write_text(contents)
    return temp_file_path
# ✨

  async def test_init_valid_python_marker(self) -> None:
    """Successful construction with valid Python marker."""
    # ✨ test init valid python marker
    name = MarkerName("test init valid python marker")
    value = '''# ✨ test init valid python marker
    a = 1 + 1
    # ✨'''
    expected_comment_char = "#"
    marker = MarkerImplementation(name, value, expected_comment_char)
    self.assertEqual(marker.name, name)
    self.assertEqual(marker.value, value)
# ✨

  async def test_init_valid_javascript_marker(self) -> None:
    """Successful construction with valid JavaScript marker."""
    # ✨ test init valid javascript marker
    name = MarkerName("test init valid javascript marker")
    value = '''// ✨ test init valid javascript marker
    let b = 2 + 2;
    // ✨'''
    expected_comment_char = "//"
    marker = MarkerImplementation(name, value, expected_comment_char)
    self.assertEqual(marker.name, name)
    self.assertEqual(marker.value, value)
# ✨

  async def test_init_empty_value_raises_error(self) -> None:
    """Constructor raises `ValueError` when `value` is an empty string."""
    # ✨ test init empty value raises error
    name = MarkerName("test init empty value raises error")
    value = ""
    expected_comment_char = "#"
    with self.assertRaisesRegex(ValueError,
                                "Implementation value cannot be empty."):
      MarkerImplementation(name, value, expected_comment_char)
# ✨

  async def test_init_single_line_valid_marker(self) -> None:
    """Successful constructor for a valid single-line implementation."""
    # ✨ test init single line valid marker
    name = MarkerName("test init single line valid marker")
    value = '''# ✨ test init single line valid marker
    pass
    # ✨'''
    expected_comment_char = "#"
    marker = MarkerImplementation(name, value, expected_comment_char)
    self.assertEqual(marker.name, name)
    self.assertEqual(marker.value, value)
# ✨

  async def test_init_incorrect_start_marker_name_raises_error(self) -> None:
    """Constructor raises `ValueError` when `value` has an invalid name.

    Example: value starts with "# ✨ foo", but marker's name is "foo bar"."""
    # ✨ test init incorrect marker name raises error
    name = MarkerName("correct marker name")
    value = '''# ✨ incorrect marker name
    a = 1 + 1
    # ✨'''
    expected_comment_char = "#"
    with self.assertRaisesRegex(
        ValueError,
        r"Implementation value must start with a line matching '# ✨ correct marker name'. Got: '# ✨ incorrect marker name'"
    ):
      MarkerImplementation(name, value, expected_comment_char)
# ✨

  async def test_init_no_start_marker_raises_error(self) -> None:
    """Raises `ValueError` when `value` lacks a start marker.

    Example: value starts with "# Implementation follows:"."""
    # ✨ test init incorrect start marker name raises error
    name = MarkerName("test init no start marker raises error")
    value = '''# This line does not contain the expected start marker
    some_test_code = 1
    # ✨'''
    expected_comment_char = "#"
    with self.assertRaisesRegex(
        ValueError,
        r"Implementation value must start with a line matching '# ✨ test init no start marker raises error'. Got: '# This line does not contain the expected start marker'"
    ):
      MarkerImplementation(name, value, expected_comment_char)
# ✨

  async def test_init_no_end_marker_raises_error(self) -> None:
    """Raises `ValueError` when `value` lacks an end marker."""
    # ✨ test init no end marker raises error
    name = MarkerName("test init no end marker raises error")
    value = '''# ✨ test init no end marker raises error
    some_test_code = 1
    # This line does not contain the expected end marker'''
    expected_comment_char = "#"
    with self.assertRaisesRegex(
        ValueError,
        r"Implementation value must end with a line matching '# ✨'. Got: '    # This line does not contain the expected end marker'"
    ):
      MarkerImplementation(name, value, expected_comment_char)
# ✨

  async def test_name_property(self) -> None:
    """Returns the correct marker name."""
    # ✨ test name property
    name = MarkerName("test name property")
    value = '''# ✨ test name property
    some_code = 1
    # ✨'''
    expected_comment_char = "#"
    marker = MarkerImplementation(name, value, expected_comment_char)
    self.assertEqual(marker.name, name)
# ✨

  async def test_value_property(self) -> None:
    """Returns the complete implementation value."""
    # ✨ test value property
    name = MarkerName("test value property")
    value = '''# ✨ test value property
    some_code = 1
    # ✨'''
    expected_comment_char = "#"
    marker = MarkerImplementation(name, value, expected_comment_char)
    self.assertEqual(marker.value, value)
# ✨

  async def test_save_replaces_single_marker_python_file(self) -> None:
    """Save replaces marker in a Python file with implementation value."""
    # ✨ test save replaces single marker python file
    marker_name = MarkerName("test save replaces single marker python file")
    initial_content = """# Some header
# {{🍄 test save replaces single marker python file}}
# Some footer"""
    file_path = self.temp_dir / "test_file.py"
    file_path.write_text(initial_content)

    implementation_value = '''# ✨ test save replaces single marker python file
    # This is the new implementation.
    result = 1 + 1
    # ✨'''
    comment_char = "#"

    marker_implementation = MarkerImplementation(marker_name,
                                                 implementation_value,
                                                 comment_char)
    await marker_implementation.save(file_path)

    final_content = file_path.read_text()

    expected_content = """# Some header
# ✨ test save replaces single marker python file
    # This is the new implementation.
    result = 1 + 1
    # ✨
# Some footer"""
    self.assertEqual(final_content.strip(), expected_content.strip())
# ✨

  async def test_save_replaces_single_marker_javascript_file(self) -> None:
    """Save replaces marker in a JavaScript file with implementation value."""
    # ✨ test save replaces single marker javascript file
    marker_name = MarkerName("test save replaces single marker javascript file")
    initial_content = """// Some header
// {{🍄 test save replaces single marker javascript file}}
// Some footer"""
    file_path = self.temp_dir / "test_file.js"
    file_path.write_text(initial_content)

    implementation_value = '''// ✨ test save replaces single marker javascript file
    // This is the new JavaScript implementation.
    let result = 2 + 2;
    // ✨'''
    comment_char = "//"

    marker_implementation = MarkerImplementation(marker_name,
                                                 implementation_value,
                                                 comment_char)
    await marker_implementation.save(file_path)

    final_content = file_path.read_text()

    expected_content = """// Some header
// ✨ test save replaces single marker javascript file
    // This is the new JavaScript implementation.
    let result = 2 + 2;
    // ✨
// Some footer"""
    self.assertEqual(final_content.strip(), expected_content.strip())
# ✨

  async def test_save_marker_not_found_raises_error(self) -> None:
    """Raises `ValueError` when target file lacks specified marker."""
    # ✨ test save marker not found raises error
    marker_name = MarkerName("test save marker not found raises error")
    initial_content = """# Some header
# Another line
# Some footer"""

    # Create a temporary .py file instead of .txt
    file_path = self.temp_dir / "test_file.py"
    file_path.write_text(initial_content)

    implementation_value = '''# ✨ test save marker not found raises error
    # This implementation won't be used as the marker isn't found.
    # ✨'''
    comment_char = "#"

    marker_implementation = MarkerImplementation(marker_name,
                                                 implementation_value,
                                                 comment_char)

    with self.assertRaisesRegex(
        ValueError,
        f"Marker '.*' found 0 times in '.*'. Expected exactly one."):
      await marker_implementation.save(file_path)
# ✨

  async def test_save_multiple_markers_raises_error(self) -> None:
    """Raises `ValueError` when target file contains marker multiple times."""
    # ✨ test save multiple markers raises error
    marker_name = MarkerName("test save multiple markers raises error")
    initial_content = """# Some header
# {{🍄 test save multiple markers raises error}}
# Some middle content
# {{🍄 test save multiple markers raises error}}
# Some footer"""
    file_path = self.temp_dir / "test_multiple_markers.py"
    file_path.write_text(initial_content)

    implementation_value = '''# ✨ test save multiple markers raises error
    # This implementation won't be used.
    # ✨'''
    comment_char = "#"

    marker_implementation = MarkerImplementation(marker_name,
                                                 implementation_value,
                                                 comment_char)

    with self.assertRaisesRegex(
        ValueError,
        f"Marker '{{{{🍄 {marker_name}}}}}' found 2 times in '.*'. Expected exactly one."
    ):
      await marker_implementation.save(file_path)
# ✨

  async def test_save_implementation_with_leading_and_trailing_whitespace(
      self) -> None:
    """Successfully handles leading/trailing whitespace around marker name.

    Example: line is: "# {{" + "🍄   my marker foo   }}"."""
    # ✨ test save implementation with leading and trailing whitespace
    logging.info("Startig XXX")
    marker_name = MarkerName(
        "test save implementation with leading and trailing whitespace")
    initial_content = """# Some header
#   {{🍄   test save implementation with leading and trailing whitespace    }}
# Some footer"""
    file_path = self.temp_dir / "test_file_whitespace.py"
    file_path.write_text(initial_content)

    implementation_value = '''# ✨ test save implementation with leading and trailing whitespace
    # This is an implementation with leading/trailing whitespace handling.
    whitespace_handled = True
    # ✨'''
    comment_char = "#"

    marker_implementation = MarkerImplementation(marker_name,
                                                 implementation_value,
                                                 comment_char)
    await marker_implementation.save(file_path)

    final_content = file_path.read_text()

    expected_content = """# Some header
# ✨ test save implementation with leading and trailing whitespace
    # This is an implementation with leading/trailing whitespace handling.
    whitespace_handled = True
    # ✨
# Some footer"""
    self.assertEqual(final_content.strip(), expected_content.strip())


# ✨

if __name__ == '__main__':
  unittest.main()
