# DO NOT EDIT. This file is automatically generated by Duende.
# DM validator:
#
# mypy $DMPATH && $PYTHON -m pytest $DMPATH
#
# See src/test-constraints.md for constraints that apply to these tests.

import aiofiles
import asyncio
import pathlib
import tempfile
import unittest
from typing import Awaitable, Callable
from unittest import mock

from agent_command import Argument, ArgumentContentType, CommandInput, CommandOutput, VariableMap, VariableName, VariableValueStr
from agent_loop import AgentLoopFactory
from agent_loop_options import AgentLoopOptions, BaseAgentLoopFactory
from agent_workflow_options import AgentWorkflowOptions
from code_specs import FileExtension, MarkerName, comment_string, relevant_paths_variable
from code_specs_agent import prepare_command_registry, prepare_initial_message, run_agent_loop
from code_specs_path_and_validator import PathAndValidator
from code_specs_validator import Validator
from code_specs_workflow import CodeSpecsWorkflow, dm_path_variable, validator_variable, implementation_variable
from command_registry import CommandRegistry
from conversation import ConversationFactory, ConversationFactoryOptions, Conversation
from conversation_state import ConversationState
from conversational_ai_test_utils import FakeConversationalAIConversation, FakeConversationalAI
from done_command import DoneCommand, DoneValuesValidator
from file_access_policy import FileAccessPolicy
from list_files_command import ListFilesCommand
from message import ContentSection, Message
from read_file_command import ReadFileCommand
from search_file_command import SearchFileCommand
from selection_manager import SelectionManager
from test_utils import FakeFileAccessPolicy, FakeConfirmationState, FakeConfirmationManager, FakeSelectionManager, slow_conversation_factory_options
from validation import ValidationResult


class TestCodeSpecsWorkflow(unittest.IsolatedAsyncioTestCase):

  def setUp(self) -> None:
    self.conversation_factory: ConversationFactory = ConversationFactory(
        slow_conversation_factory_options())

  async def build_workflow(
      self, scripted_messages: dict[str, list[Message]]) -> CodeSpecsWorkflow:
    """Sets up a CodeSpecWorkflow with fake objects.

    Sets option skip_implicit_validation to True.
    """
    # ✨ build workflow
    conversational_ai = FakeConversationalAI(scripted_messages)
    file_access_policy = FakeFileAccessPolicy()
    confirmation_state = FakeConfirmationState(FakeConfirmationManager())

    # Create command_registry before conversation if it's needed by ConversationFactory.New
    command_registry = CommandRegistry()

    # Pass command_registry to ConversationFactory.New based on mypy error
    conversation = self.conversation_factory.New("dummy", command_registry)

    agent_loop_options = AgentLoopOptions(
        conversation=conversation,
        start_message=Message("user",
                              [ContentSection("Initial placeholder message")]),
        command_registry=command_registry,  # Use the already created command_registry
        confirmation_state=confirmation_state,
        file_access_policy=file_access_policy,
        conversational_ai=conversational_ai,
        confirm_regex=None,
        skip_implicit_validation=True,
        validation_manager=None,
    )

    agent_workflow_options = AgentWorkflowOptions(
        agent_loop_options=agent_loop_options,
        agent_loop_factory=AgentLoopFactory(),
        conversation_factory=self.conversation_factory,
        selection_manager=FakeSelectionManager(),
        principle_paths=None,
        input_paths=None,
        original_task_prompt_content=None,
        confirm_done='',
        do_review=False,
        review_first=False,
    )

    return CodeSpecsWorkflow(agent_workflow_options)
    # ✨

  def filter_content_sections(
      self, predicate: Callable[[ContentSection],
                                bool]) -> list[ContentSection]:
    """Returns any content sections in any messages that match a predicate.

    Extracts the messages from self.conversation_factory."""

    # ✨ filter content sections
    matching_sections: list[ContentSection] = []
    for conversation in self.conversation_factory.GetAll():
      for message in conversation.GetMessagesList():
        for section in message.GetContentSections():
          if predicate(section):
            matching_sections.append(section)
    return matching_sections
    # ✨

  async def test_codespecsworkflow__get_initial_parameters_the_done_command_arguments_given_to_prepare_command_registry_are_dm_path_variable_and_validator_variable_1(
      self) -> None:
    # ✨ The done command arguments given to `prepare_command_registry` are `dm_path_variable` and `validator_variable`. (in CodeSpecsWorkflow._get_initial_parameters)
    with tempfile.TemporaryDirectory() as temp_dir:
      temp_dm_path = pathlib.Path(temp_dir) / "my_component.dm.py"

      mushroom_char = "🍄"
      marker_name_in_file = "simple_marker"

      literal_marker_in_file = "# " + '{' + '{' + "🍄 simple marker" + '}' + '}'

      # Create a dummy DM file with a very simple mushroom marker.
      content = ("# A very simple dm.py file\n" + literal_marker_in_file + "\n"
                 "def some_function():\n"
                 "  pass\n")
      temp_dm_path.write_text(content, encoding='utf-8')

      dm_path_value = str(temp_dm_path)
      # Use a validator that always succeeds and includes $DMPATH as required by PathAndValidator.
      validator_value = "true $DMPATH"

      # Scripted messages to simulate the agent calling 'done' with the required parameters.
      scripted_messages = {
          "initial_parameters": [
              Message(
                  role="assistant",
                  content_sections=[
                      ContentSection(
                          content="",
                          command=CommandInput(
                              command_name="done",
                              args=VariableMap({
                                  dm_path_variable:
                                      VariableValueStr(dm_path_value),
                                  validator_variable:
                                      VariableValueStr(validator_value),
                              }),
                          ))
                  ])
          ]
      }

      workflow = await self.build_workflow(scripted_messages)
      # Expecting _get_initial_parameters to complete successfully now.
      path_and_validator = await workflow._get_initial_parameters()

      # Get the conversation created by _get_initial_parameters
      # Find the conversation by name, as there might be other dummy conversations.
      conversation = None
      for conv in self.conversation_factory.GetAll():
        if conv.GetName() == "initial_parameters":
          conversation = conv
          break
      self.assertIsNotNone(conversation,
                           "Conversation 'initial_parameters' not found.")
      assert conversation is not None  # For mypy narrowing

      # Get the command registry from the conversation (it should have been set during conversation creation)
      command_registry = conversation.command_registry
      self.assertIsInstance(command_registry, CommandRegistry)

      # Retrieve the DoneCommand using its public name
      agent_command = command_registry.Get("done")

      # Assert that it's a DoneCommand instance for the unit test framework
      self.assertIsInstance(agent_command, DoneCommand,
                            "Retrieved command is not a DoneCommand instance.")

      # Assert that it's a DoneCommand instance for mypy's type narrowing
      assert isinstance(
          agent_command,
          DoneCommand), "Retrieved command is not a DoneCommand instance."

      # Now, agent_command is narrowed to DoneCommand
      # Assertions on agent_command's arguments
      self.assertEqual(len(agent_command.Syntax().arguments), 2)
      self.assertEqual(agent_command.Syntax().arguments[0].name,
                       dm_path_variable)
      self.assertEqual(agent_command.Syntax().arguments[0].arg_type,
                       ArgumentContentType.PATH_INPUT)
      self.assertEqual(agent_command.Syntax().arguments[1].name,
                       validator_variable)
      self.assertEqual(agent_command.Syntax().arguments[1].arg_type,
                       ArgumentContentType.STRING)

      # Additionally, assert that the returned PathAndValidator has the correct values
      self.assertEqual(path_and_validator.dm_path, pathlib.Path(dm_path_value))
      self.assertEqual(path_and_validator.validator.command, validator_value)
    # ✨

  async def test_codespecsworkflow__get_initial_parameters_does_not_enable_caching_of_conversations_through_output_cache_1(
      self) -> None:
    # ✨ Does *not* enable caching of conversations (through output_cache). (in CodeSpecsWorkflow._get_initial_parameters)
    import output_cache  # Import output_cache for CachingDelegatingAgentLoopFactory

    with tempfile.TemporaryDirectory() as temp_dir:
      temp_dm_path = pathlib.Path(temp_dir) / "my_component.dm.py"

      # Construct the literal string for the marker line that goes into the temporary file.
      literal_marker_in_file = "# {{" + "🍄 simple marker}}"

      # Create a dummy DM file with a very simple mushroom marker.
      content = "# A very simple dm.py file\n"
      content += f"{literal_marker_in_file}\n"
      content += "def some_function():\n"
      content += "  pass\n"
      temp_dm_path.write_text(content, encoding='utf-8')

      dm_path_value = str(temp_dm_path)
      # Use a validator that always succeeds and includes $DMPATH as required by PathAndValidator.
      validator_value = "true $DMPATH"

      # Scripted messages for two calls to _get_initial_parameters.
      # Each call to run_agent_loop (for conversation "initial_parameters") will consume one 'done' command.
      two_done_commands = [
          Message(
              role="assistant",
              content_sections=[
                  ContentSection(
                      content="",
                      command=CommandInput(
                          command_name="done",
                          args=VariableMap({
                              dm_path_variable:
                                  VariableValueStr(dm_path_value),
                              validator_variable:
                                  VariableValueStr(validator_value),
                          }),
                      ))
              ]) for _ in range(2)  # Repeat the done command twice
      ]

      scripted_messages = {
          "initial_parameters": two_done_commands
      }

      workflow = await self.build_workflow(scripted_messages)

      # Get the initial agent_loop_factory instance before calling _get_initial_parameters
      initial_agent_loop_factory = workflow._options.agent_loop_factory

      # First call to the method under test
      path_and_validator_1 = await workflow._get_initial_parameters()

      # Get conversations specifically named "initial_parameters"
      initial_parameters_conversations_1 = [
          c for c in self.conversation_factory.GetAll()
          if c.GetName() == "initial_parameters"
      ]

      self.assertEqual(len(initial_parameters_conversations_1), 1,
                       "Expected exactly one 'initial_parameters' conversation after the first call.")
      first_conversation = initial_parameters_conversations_1[0]

      # Get the agent_loop_factory instance after the first call
      final_agent_loop_factory_1 = workflow._options.agent_loop_factory

      # Assert that the agent_loop_factory instance is the same object
      # and has not been replaced by a caching factory after the first call.
      self.assertIs(initial_agent_loop_factory, final_agent_loop_factory_1)
      self.assertIsInstance(final_agent_loop_factory_1, AgentLoopFactory)
      self.assertNotIsInstance(
          final_agent_loop_factory_1,
          output_cache.CachingDelegatingAgentLoopFactory,
          "CachingDelegatingAgentLoopFactory found after first call, indicating caching was enabled unexpectedly.")

      # Additionally, assert that the returned PathAndValidator has the correct values for the first call
      self.assertEqual(path_and_validator_1.dm_path, pathlib.Path(dm_path_value))
      self.assertEqual(path_and_validator_1.validator.command, validator_value)

      # Second call to the method under test
      path_and_validator_2 = await workflow._get_initial_parameters()

      # Get conversations specifically named "initial_parameters" after the second call
      initial_parameters_conversations_2 = [
          c for c in self.conversation_factory.GetAll()
          if c.GetName() == "initial_parameters"
      ]

      self.assertEqual(len(initial_parameters_conversations_2), 2,
                       "Expected exactly two 'initial_parameters' conversations after the second call.")

      # Find the second conversation (which should be different from the first)
      second_conversation = None
      for conv in initial_parameters_conversations_2:
          if conv != first_conversation:
              second_conversation = conv
              break
      self.assertIsNotNone(second_conversation, "Second conversation object was not found or is the same as the first.")

      # Assert that the two conversations are distinct objects, proving a new conversation was started.
      self.assertIsNot(first_conversation, second_conversation,
                       "Expected a new conversation object, but the same one was reused.")

      # Get the agent_loop_factory instance after the second call
      final_agent_loop_factory_2 = workflow._options.agent_loop_factory

      # Assert that the agent_loop_factory instance is still the same object
      # and has not been replaced by a caching factory after the second call.
      self.assertIs(initial_agent_loop_factory, final_agent_loop_factory_2)
      self.assertIsInstance(final_agent_loop_factory_2, AgentLoopFactory)
      self.assertNotIsInstance(
          final_agent_loop_factory_2,
          output_cache.CachingDelegatingAgentLoopFactory,
          "CachingDelegatingAgentLoopFactory found after second call, indicating caching was enabled unexpectedly.")

      # Additionally, assert that the returned PathAndValidator has the correct values for the second call
      self.assertEqual(path_and_validator_2.dm_path, pathlib.Path(dm_path_value))
      self.assertEqual(path_and_validator_2.validator.command, validator_value)
    # ✨

  async def test_codespecsworkflow__get_initial_parameters_done_validator_if_the_dm_path_has_repeated_identical_mushroom_markers_per_code_specsget_markers_validation_fails_with_an_explanation_1(
      self) -> None:

    # ✨ If the dm_path has repeated (identical) MUSHROOM markers (per `code_specs.get_markers`), validation fails with an explanation. (in CodeSpecsWorkflow._get_initial_parameters.done_validator)
    # No mocks allowed.
    import asyncio  # For async functions
    import code_specs_workflow
    from agent_command import CommandInput, VariableMap, VariableName, VariableValueStr
    from message import ContentSection, Message
    from conversational_ai_test_utils import FakeConversationalAI
    from validation import ValidationResult  # Re-adding this import as it's a type used by done_validator

    with tempfile.TemporaryDirectory() as temp_dir:
      # --- Failing DM path setup ---
      temp_dm_path_failing = pathlib.Path(temp_dir) / "failing.dm.py"
      mushroom_char_escaped = chr(0x1F344)
      # Corrected marker string: no space after "{{"
      mushroom_marker_failing_str = "{{" + mushroom_char_escaped + " RepeatedMarker}}"
      content_failing = f"""# A dm.py file with repeated markers
    {mushroom_marker_failing_str}
    # Some code in between
    {mushroom_marker_failing_str}
    def some_function_failing():
      pass
    """
      temp_dm_path_failing.write_text(content_failing, encoding='utf-8')
      dm_path_value_failing = str(temp_dm_path_failing)

      # --- Succeeding DM path setup ---
      temp_dm_path_succeeding = pathlib.Path(temp_dir) / "succeeding.dm.py"
      # Corrected marker string: no space after "{{"
      mushroom_marker_succeeding_str = "{{" + mushroom_char_escaped + " SingleMarker}}"
      content_succeeding = f"""# A dm.py file with a single marker
    {mushroom_marker_succeeding_str}
    def some_function_succeeding():
      pass
    """
      temp_dm_path_succeeding.write_text(content_succeeding, encoding='utf-8')
      dm_path_value_succeeding = str(temp_dm_path_succeeding)

      validator_value = "true $DMPATH"

      scripted_messages = {
          "initial_parameters": [
              # First attempt: fails validation due to repeated markers
              Message(
                  role="assistant",
                  content_sections=[
                      ContentSection(
                          content="",
                          command=CommandInput(
                              command_name="done",
                              args=VariableMap({
                                  dm_path_variable:
                                      VariableValueStr(dm_path_value_failing),
                                  validator_variable:
                                      VariableValueStr(validator_value),
                              }),
                          ))
                  ]),
              # Second attempt: succeeds validation
              Message(
                  role="assistant",
                  content_sections=[
                      ContentSection(
                          content="",
                          command=CommandInput(
                              command_name="done",
                              args=VariableMap({
                                  dm_path_variable:
                                      VariableValueStr(dm_path_value_succeeding
                                                      ),
                                  validator_variable:
                                      VariableValueStr(validator_value),
                              }),
                          ))
                  ])
          ]
      }

      workflow = await self.build_workflow(scripted_messages)

      # Call _get_initial_parameters, expecting it to complete successfully after retries.
      # The successful return value will be from the second `done` call.
      path_and_validator = await workflow._get_initial_parameters()

      # Assert that the returned PathAndValidator is based on the succeeding path.
      self.assertEqual(path_and_validator.dm_path, temp_dm_path_succeeding)
      self.assertEqual(path_and_validator.validator.command, validator_value)

      # Find the conversation named "initial_parameters".
      conversation = None
      for conv in self.conversation_factory.GetAll():
        if conv.GetName() == "initial_parameters":
          conversation = conv
          break
      self.assertIsNotNone(conversation,
                           "Conversation 'initial_parameters' not found.")
      assert conversation is not None

      # Check if any message from the user (containing a system error) contains the expected error.
      found_error_message_in_conversation = False

      # Construct the expected error string, including the "Error: " prefix and dynamic path.
      # Use chr(0x1F344) for the mushroom character.
      full_expected_error_message = (
          f"Error: Invalid parameters for PathAndValidator: Repeated {chr(0x1F344)} marker 'RepeatedMarker' found in '{dm_path_value_failing}' at lines: 1, 3. "
          "Each marker name must be unique.")

      for message in conversation.GetMessagesList():
        if message.role == "user":  # Look for user role messages, as FakeConversationalAI presents system errors as user messages.
          for section in message.GetContentSections():
            if section.content == full_expected_error_message:  # Use exact match for clarity
              found_error_message_in_conversation = True
              break
          if found_error_message_in_conversation:
            break
      self.assertTrue(
          found_error_message_in_conversation,
          f"Expected error message '{full_expected_error_message}' not found in conversation history. Actual message roles: {[m.role for m in conversation.GetMessagesList()]}. Actual content sections: {[s.content for m in conversation.GetMessagesList() for s in m.GetContentSections()]}."
      )

    # ✨

  async def test_codespecsworkflow__get_initial_parameters_done_validator_catches_exceptions_from_pathandvalidator_and_turns_them_into_a_failed_validationresult_1(
      self) -> None:
    # ✨ Catches exceptions from PathAndValidator and turns them into a failed `ValidationResult`. (in CodeSpecsWorkflow._get_initial_parameters.done_validator)
    # No mocks allowed.
    import asyncio  # For async functions
    import code_specs_workflow
    from agent_command import CommandInput, VariableMap, VariableName, VariableValueStr
    from message import ContentSection, Message
    from conversational_ai_test_utils import FakeConversationalAI
    from validation import ValidationResult  # Re-adding this import as it's a type used by done_validator

    with tempfile.TemporaryDirectory() as temp_dir:
      # --- Failing DM path setup: Missing .dm. ---
      temp_dm_path_failing = pathlib.Path(temp_dir) / "no_dm_part.py"
      # Create an empty file, as PathAndValidator will still check if it exists
      temp_dm_path_failing.write_text("", encoding='utf-8')
      dm_path_value_failing = str(temp_dm_path_failing)

      # --- Succeeding DM path setup ---
      temp_dm_path_succeeding = pathlib.Path(temp_dir) / "succeeding.dm.py"
      mushroom_char_escaped = chr(0x1F344)  # 🍄
      mushroom_marker_succeeding_str = "{{" + mushroom_char_escaped + " SingleMarker}}"
      content_succeeding = f"""# A dm.py file with a single marker
    {mushroom_marker_succeeding_str}
    def some_function_succeeding():
      pass
    """
      temp_dm_path_succeeding.write_text(content_succeeding, encoding='utf-8')
      dm_path_value_succeeding = str(temp_dm_path_succeeding)

      validator_value = "true $DMPATH"

      scripted_messages = {
          "initial_parameters": [
              # First attempt: fails validation because dm_path is missing '.dm.'
              Message(
                  role="assistant",
                  content_sections=[
                      ContentSection(
                          content="",
                          command=CommandInput(
                              command_name="done",
                              args=VariableMap({
                                  dm_path_variable:
                                      VariableValueStr(dm_path_value_failing),
                                  validator_variable:
                                      VariableValueStr(validator_value),
                              }),
                          ))
                  ]),
              # Second attempt: succeeds validation
              Message(
                  role="assistant",
                  content_sections=[
                      ContentSection(
                          content="",
                          command=CommandInput(
                              command_name="done",
                              args=VariableMap({
                                  dm_path_variable:
                                      VariableValueStr(dm_path_value_succeeding
                                                      ),
                                  validator_variable:
                                      VariableValueStr(validator_value),
                              }),
                          ))
                  ])
          ]
      }

      workflow = await self.build_workflow(scripted_messages)

      # Call _get_initial_parameters, expecting it to complete successfully after retries.
      path_and_validator = await workflow._get_initial_parameters()

      # Assert that the returned PathAndValidator is based on the succeeding path.
      self.assertEqual(path_and_validator.dm_path, temp_dm_path_succeeding)
      self.assertEqual(path_and_validator.validator.command, validator_value)

      # Find the conversation named "initial_parameters".
      conversation = None
      for conv in self.conversation_factory.GetAll():
        if conv.GetName() == "initial_parameters":
          conversation = conv
          break
      self.assertIsNotNone(conversation,
                           "Conversation 'initial_parameters' not found.")
      assert conversation is not None

      # Check if any message from the user (containing a system error) contains the expected error.
      found_error_message_in_conversation = False

      # Construct the expected error string for the ValueError from PathAndValidator's validate_fields.
      # The error message should be "Invalid parameters for PathAndValidator: `dm_path` ('<path>') must contain '.dm.'."
      full_expected_error_message = (
          f"Error: Invalid parameters for PathAndValidator: `dm_path` ('{dm_path_value_failing}') must contain '.dm.'."
      )

      for message in conversation.GetMessagesList():
        if message.role == "user":  # System errors are presented as user messages by FakeConversationalAI
          for section in message.GetContentSections():
            if section.content == full_expected_error_message:
              found_error_message_in_conversation = True
              break
          if found_error_message_in_conversation:
            break
      self.assertTrue(
          found_error_message_in_conversation,
          f"Expected error message '{full_expected_error_message}' not found in conversation history. Actual content sections: {[s.content for m in conversation.GetMessagesList() for s in m.GetContentSections()]}."
      )

    # ✨

  async def test_codespecsworkflow__prepare_output_path_if_it_exists_inputoutput_path_is_copied_to_inputold_path_1(
      self) -> None:
    # ✨ If it exists, `input.output_path()` is copied to `input.old_path()`. (in CodeSpecsWorkflow._prepare_output_path)
    # No mocks allowed.

    with tempfile.TemporaryDirectory() as temp_dir:
      temp_path = pathlib.Path(temp_dir)

      # 1. Setup: Create dummy dm_path and an existing output_path
      dm_file_name = "my_module.dm.py"
      output_file_name = "my_module.py"
      old_file_name = "my_module.old.py"  # This is derived from output_path and input.old_path()

      dm_path = temp_path / dm_file_name
      output_path = temp_path / output_file_name
      old_path = temp_path / old_file_name

      # Content for the dm_path
      dm_file_content = """# Some code from DM file
    def dm_function():
      pass
    # {{' + '🍄 MyMarker' + '}}
    """
      # Original content for the output_path, which should be copied to old_path
      output_file_original_content = """# Original content of output file
    class MyClass:
      def __init__(self):
        pass
    """
      # Write the dummy files
      dm_path.write_text(dm_file_content, encoding='utf-8')
      output_path.write_text(output_file_original_content, encoding='utf-8')

      # Create a PathAndValidator instance
      # Validator command now includes $DMPATH to pass validation.
      path_and_validator = PathAndValidator(
          dm_path=dm_path, validator=Validator(command="true $DMPATH"))

      # Ensure the output_path and old_path derived by PathAndValidator match our expectations
      self.assertEqual(path_and_validator.output_path(), output_path)
      self.assertEqual(path_and_validator.old_path(), old_path)

      # Sanity check: old_path should not exist initially
      self.assertFalse(old_path.exists())
      self.assertTrue(output_path.exists())

      # 2. Call the method under test
      # We don't need scripted_messages or a conversational_ai for this direct method call.
      # The build_workflow method expects scripted_messages, so we provide an empty dict.
      workflow = await self.build_workflow(scripted_messages={})
      await workflow._prepare_output_path(path_and_validator)

      # 3. Assertions
      # Assert that old_path now exists
      self.assertTrue(old_path.exists())

      # Assert that the content of old_path is the original content of output_path
      self.assertEqual(
          old_path.read_text(encoding='utf-8'), output_file_original_content)

      # Assert that output_path has been overwritten with dm_file_content,
      # prefixed with the auto-generated comment.
      expected_output_content_prefix = comment_string(
          FileExtension("py"),
          "DO NOT EDIT. This file is automatically generated by Duende.")
      expected_output_content = expected_output_content_prefix + "\n" + dm_file_content
      self.assertEqual(
          output_path.read_text(encoding='utf-8'), expected_output_content)
    # ✨

  async def test_codespecsworkflow__prepare_output_path_unconditionally_overwrites_inputoutput_path_with_inputdm_path_after_copying_it_to_old_path_1(
      self) -> None:
    # ✨ Unconditionally overwrites `input.output_path()` with `input.dm_path` (after copying it to `old_path`). (in CodeSpecsWorkflow._prepare_output_path)
    import asyncio  # For async functions

    with tempfile.TemporaryDirectory() as temp_dir:
      temp_path = pathlib.Path(temp_dir)

      # 1. Setup: Create dummy dm_path, and ensure output_path and old_path do NOT exist
      dm_file_name = "my_module.dm.py"
      output_file_name = "my_module.py"
      old_file_name = "my_module.old.py"

      dm_path = temp_path / dm_file_name
      output_path = temp_path / output_file_name
      old_path = temp_path / old_file_name

      # Content for the dm_path
      dm_file_content = '''# Some code from DM file
    def dm_function():
      return 123
    '''
      # Write the dummy dm_path file
      dm_path.write_text(dm_file_content, encoding='utf-8')

      # Ensure output_path and old_path do NOT exist initially for this test case
      self.assertFalse(output_path.exists())
      self.assertFalse(old_path.exists())

      # Create a PathAndValidator instance
      # The validator command must include $DMPATH for PathAndValidator to be valid.
      path_and_validator = PathAndValidator(
          dm_path=dm_path, validator=Validator(command="true $DMPATH"))

      # Ensure the output_path and old_path derived by PathAndValidator match our expectations
      self.assertEqual(path_and_validator.output_path(), output_path)
      self.assertEqual(path_and_validator.old_path(), old_path)

      # 2. Call the method under test
      workflow = await self.build_workflow(scripted_messages={})
      await workflow._prepare_output_path(path_and_validator)

      # 3. Assertions
      # Assert that old_path still does NOT exist, as output_path was not present to be copied
      self.assertFalse(old_path.exists())

      # Assert that output_path now exists (it was created and populated)
      self.assertTrue(output_path.exists())

      # Assert that output_path has been populated with dm_file_content,
      # prefixed with the auto-generated comment.
      expected_output_content_prefix = comment_string(
          FileExtension("py"),
          "DO NOT EDIT. This file is automatically generated by Duende.")
      expected_output_content = expected_output_content_prefix + "\n" + dm_file_content
      self.assertEqual(
          output_path.read_text(encoding='utf-8'), expected_output_content)
    # ✨

  async def test_codespecsworkflow__find_relevant_paths_calls_find_relevant_paths_for_marker_exactly_once_for_each_marker_found_in_path_1(
      self) -> None:
        # ✨ Calls `find_relevant_paths_for_marker` exactly once for each marker found in `path`. (in CodeSpecsWorkflow._find_relevant_paths)
        import code_specs
        from collections import OrderedDict
        import os # Needed for os.access check in done_validate

        with tempfile.TemporaryDirectory() as temp_dir:
          temp_path = pathlib.Path(temp_dir)

          # 1. Setup: Create a dummy DM file with multiple unique markers
          dm_file_name = "multi_marker.dm.py"
          dm_path = temp_path / dm_file_name

          marker1_name_str = "MarkerOne"
          marker2_name_str = "MarkerTwo"
          marker3_name_str = "MarkerThree"

          # Use chr(0x1F344) to insert the mushroom character without having it as a literal in the test file itself.
          mushroom_char_str = chr(0x1F344)

          # Define MarkerName objects for our test markers (using the actual MUSHROOM constant in code_specs_workflow)
          from code_specs_workflow import MUSHROOM as ACTUAL_MUSHROOM_CHAR
          marker1_obj = code_specs.MarkerName(char=ACTUAL_MUSHROOM_CHAR, name=code_specs.MarkerChar(marker1_name_str))
          marker2_obj = code_specs.MarkerName(char=ACTUAL_MUSHROOM_CHAR, name=code_specs.MarkerChar(marker2_name_str))
          marker3_obj = code_specs.MarkerName(char=ACTUAL_MUSHROOM_CHAR, name=code_specs.MarkerChar(marker3_name_str))


          content = f"""# DM file with multiple markers
    # {{{{{mushroom_char_str} {marker1_name_str}}}}}
    # Some code for marker one
    # {{{{{mushroom_char_str} {marker2_name_str}}}}}
    # Some code for marker two
    # {{{{{mushroom_char_str} {marker3_name_str}}}}}
    # Some code for marker three
    """
          dm_path.write_text(content, encoding='utf-8')

          # Create actual dummy files for the "relevant paths" within the temporary directory
          file1_path = temp_path / "file_one.py"
          file2_path = temp_path / "file_two.py"
          file3_path = temp_path / "file_three.py"
          file_another_path = temp_path / "file_another.py"

          file1_path.write_text("content for file one")
          file2_path.write_text("content for file two")
          file3_path.write_text("content for file three")
          file_another_path.write_text("content for another file")

          # Paths that _find_relevant_paths_for_marker will return for each marker
          paths_for_marker1 = {file1_path}
          paths_for_marker2 = {file2_path, file_another_path}
          paths_for_marker3 = {file3_path}

          # 2. Script FakeConversationalAI to provide responses for _get_initial_parameters
          # and each call to _find_relevant_paths_for_marker
          scripted_messages = {
              "initial_parameters": [
                  Message(
                      role="assistant",
                      content_sections=[
                          ContentSection(
                              content="",
                              command=CommandInput(
                                  command_name="done",
                                  args=VariableMap({
                                      dm_path_variable: VariableValueStr(str(dm_path)),
                                      validator_variable: VariableValueStr("true $DMPATH"),
                                  }),
                              ))
                      ])
              ],
              f"find_relevant_paths_for_{marker1_name_str}": [
                  Message(
                      role="assistant",
                      content_sections=[
                          ContentSection(
                              content="",
                              command=CommandInput(
                                  command_name="done",
                                  args=VariableMap({
                                      relevant_paths_variable: VariableValueStr(','.join(str(p) for p in paths_for_marker1)),
                                  }),
                              ))
                      ])
              ],
              f"find_relevant_paths_for_{marker2_name_str}": [
                  Message(
                      role="assistant",
                      content_sections=[
                          ContentSection(
                              content="",
                              command=CommandInput(
                                  command_name="done",
                                  args=VariableMap({
                                      relevant_paths_variable: VariableValueStr(','.join(str(p) for p in paths_for_marker2)),
                                  }),
                              ))
                      ])
              ],
              f"find_relevant_paths_for_{marker3_name_str}": [
                  Message(
                      role="assistant",
                      content_sections=[
                          ContentSection(
                              content="",
                              command=CommandInput(
                                  command_name="done",
                                  args=VariableMap({
                                      relevant_paths_variable: VariableValueStr(','.join(str(p) for p in paths_for_marker3)),
                                  }),
                              ))
                      ])
              ],
          }

          workflow = await self.build_workflow(scripted_messages)

          # First, run the _get_initial_parameters call, which will use the "initial_parameters" script.
          initial_path_and_validator = await workflow._get_initial_parameters()

          # Then, run _prepare_output_path. This will create the output file at initial_path_and_validator.output_path()
          # with the content of dm_path and the "DO NOT EDIT" header.
          await workflow._prepare_output_path(initial_path_and_validator)

          # 3. Call the method under test with the output_path, which _find_relevant_paths will read.
          relevant_paths = await workflow._find_relevant_paths(initial_path_and_validator.output_path())

          # 4. Assertions
          self.assertIsInstance(relevant_paths, dict)
          self.assertEqual(len(relevant_paths), 3)

          # Check for marker1
          self.assertIn(marker1_obj, relevant_paths)
          self.assertEqual(relevant_paths[marker1_obj], paths_for_marker1)

          # Check for marker2
          self.assertIn(marker2_obj, relevant_paths)
          self.assertEqual(relevant_paths[marker2_obj], paths_for_marker2)

          # Check for marker3
          self.assertIn(marker3_obj, relevant_paths)
          self.assertEqual(relevant_paths[marker3_obj], paths_for_marker3)

          # Assert that exactly 4 conversations were created (excluding the initial "dummy" conversation).
          self.assertEqual(len([c for c in self.conversation_factory.GetAll() if c.GetName() != "dummy"]), 4)
        # ✨

  async def test_codespecsworkflow__find_relevant_paths_calls_to_find_relevant_paths_for_marker_happen_concurrently_1(
      self) -> None:
        # ✨ Calls to `find_relevant_paths_for_marker` happen concurrently. (in CodeSpecsWorkflow._find_relevant_paths)
        import asyncio
        import time
        from unittest import mock
        from collections import OrderedDict # For mock_get_markers return_value
        import code_specs # To access MarkerChar and MarkerName

        with tempfile.TemporaryDirectory() as temp_dir:
          temp_path = pathlib.Path(temp_dir)

          # 1. Setup: Create a dummy DM file with multiple unique markers
          dm_file_name = "concurrent_markers.dm.py"
          dm_path = temp_path / dm_file_name

          marker1_name_str = "ConcurrentMarkerOne"
          marker2_name_str = "ConcurrentMarkerTwo"
          marker3_name_str = "ConcurrentMarkerThree"

          mushroom_char_str = chr(0x1F344) # 🍄 (as a string literal for file content)

          content = f"""# DM file with multiple markers for concurrency test
    # {{{{{mushroom_char_str} {marker1_name_str}}}}}
    # Placeholder for marker one
    # {{{{{mushroom_char_str} {marker2_name_str}}}}}
    # Placeholder for marker two
    # {{{{{mushroom_char_str} {marker3_name_str}}}}}
    # Placeholder for marker three
    """
          dm_path.write_text(content, encoding='utf-8')

          # Create a PathAndValidator instance, needed by CodeSpecsWorkflow but not directly used by _find_relevant_paths
          # The validator command must include $DMPATH for PathAndValidator to be valid.
          path_and_validator = PathAndValidator(
              dm_path=dm_path, validator=Validator(command="true $DMPATH"))

          # 2. Build the workflow
          workflow = await self.build_workflow(scripted_messages={})

          # Prepare MarkerName objects to be consistent with get_markers and mock calls
          mushroom_marker_char = code_specs.MarkerChar(mushroom_char_str)
          marker1_obj = code_specs.MarkerName(char=mushroom_marker_char, name=marker1_name_str)
          marker2_obj = code_specs.MarkerName(char=mushroom_marker_char, name=marker2_name_str)
          marker3_obj = code_specs.MarkerName(char=mushroom_marker_char, name=marker3_name_str)

          # Mock get_markers to return our controlled MarkerName objects in a predictable order
          with mock.patch('code_specs.get_markers', new_callable=mock.AsyncMock) as mock_get_markers:
              mock_get_markers.return_value = OrderedDict([
                  (marker1_obj, []), # Line numbers don't matter for this test
                  (marker2_obj, []),
                  (marker3_obj, []),
              ])

              # Mock _find_relevant_paths_for_marker
              # We will record start and end times for each call to check for concurrency
              call_times = {} # {marker_name_str: {'start': float, 'end': float}}

              async def mock_find_relevant_paths_for_marker_impl(current_path, marker_obj):
                  marker_name_key = marker_obj.name
                  start_time = asyncio.get_event_loop().time()
                  call_times[marker_name_key] = {'start': start_time}

                  # Simulate some asynchronous work
                  await asyncio.sleep(0.1) # Small delay to allow other tasks to run

                  end_time = asyncio.get_event_loop().time()
                  call_times[marker_name_key]['end'] = end_time
                  return {current_path.parent / f"relevant_{marker_name_key}.py"}

              with mock.patch.object(
                  workflow,
                  '_find_relevant_paths_for_marker',
                  side_effect=mock_find_relevant_paths_for_marker_impl,
                  new_callable=mock.AsyncMock) as mock_find_relevant_paths_for_marker:

                  # 3. Call the method under test
                  relevant_paths = await workflow._find_relevant_paths(dm_path)

                  # 4. Assertions
                  # Ensure _find_relevant_paths_for_marker was called for each marker
                  self.assertEqual(mock_find_relevant_paths_for_marker.call_count, 3)

                  # Assert that calls happened concurrently
                  # Check if the start of a later task is before the end of an earlier task.
                  # This indicates overlap.
                  self.assertIn(marker1_name_str, call_times)
                  self.assertIn(marker2_name_str, call_times)
                  self.assertIn(marker3_name_str, call_times)

                  # Sort markers by their recorded start times to simplify concurrency checks
                  sorted_markers_by_start = sorted(call_times.items(), key=lambda item: item[1]['start'])

                  # For concurrency, at least one of the subsequent markers must have started before the first one finished.
                  # More generally, we can check if there's any overlap.
                  # A simpler check for concurrency with N tasks: the first task should not have finished before all tasks have started.
                  # Or, if tasks have equal simulated duration, the total time should be close to the duration of one task.

                  first_marker_start_time = sorted_markers_by_start[0][1]['start']
                  first_marker_end_time = sorted_markers_by_start[0][1]['end']
                  last_marker_start_time = sorted_markers_by_start[-1][1]['start']

                  # If tasks run concurrently, the last task should start before the first task finishes.
                  # This implies that while the first task was running, other tasks began.
                  self.assertLess(last_marker_start_time, first_marker_end_time,
                                  "Tasks did not appear to run concurrently; the last task only started after the first one finished.")

                  # Further check: The total elapsed time for all tasks should be significantly less than the sum of individual delays
                  # (3 * 0.1s = 0.3s) if they run concurrently.
                  # It should be closer to the longest individual task duration (0.1s in this case, plus overhead).
                  total_duration = max(t['end'] for t in call_times.values()) - min(t['start'] for t in call_times.values())
                  expected_min_duration = 0.1 # The duration of a single sleep
                  tolerance = 0.05 # Allow some overhead for task switching etc.
                  self.assertGreater(total_duration, expected_min_duration)
                  self.assertLess(total_duration, expected_min_duration * 1.5 + tolerance, # Should be less than sum of all delays if sequential
                                  f"Total duration ({total_duration:.4f}s) suggests sequential execution, expected closer to {expected_min_duration:.4f}s for concurrent. Individual durations: {[t['end'] - t['start'] for t in call_times.values()]}")

                  # Also confirm the mocked paths are returned
                  expected_relevant_paths = {
                      marker1_obj: {temp_path / "relevant_ConcurrentMarkerOne.py"},
                      marker2_obj: {temp_path / "relevant_ConcurrentMarkerTwo.py"},
                      marker3_obj: {temp_path / "relevant_ConcurrentMarkerThree.py"},
                  }
                  self.assertEqual(relevant_paths, expected_relevant_paths)
        # ✨

  async def test_codespecsworkflow__find_relevant_paths_the_output_contains_one_entry_for_each_marker_found_in_path_1(
      self) -> None:
    # ✨ The output contains one entry for each marker found in `path`. (in CodeSpecsWorkflow._find_relevant_paths)
            with tempfile.TemporaryDirectory() as temp_dir:
              temp_path = pathlib.Path(temp_dir)

              # 1. Setup: Create a dummy DM file with multiple unique markers
              dm_file_name = "multi_marker_output_test.dm.py"
              dm_path = temp_path / dm_file_name

              marker1_name_str = "OutputMarkerOne"
              marker2_name_str = "OutputMarkerTwo"
              marker3_name_str = "OutputMarkerThree"

              mushroom_char_lit = "{{" + chr(0x1F344) + " " # Start of marker with mushroom char
              end_marker_lit = "}}" # End of marker

              content = (f"# DM file for output contains one entry test\n"
                         f"# {mushroom_char_lit}{marker1_name_str}{end_marker_lit}\n"
                         f"# Code related to OutputMarkerOne\n"
                         f"# {mushroom_char_lit}{marker2_name_str}{end_marker_lit}\n"
                         f"# Code related to OutputMarkerTwo\n"
                         f"# {mushroom_char_lit}{marker3_name_str}{end_marker_lit}\n"
                         f"# Code related to OutputMarkerThree\n")
              dm_path.write_text(content, encoding='utf-8')

              # Create a PathAndValidator instance (validator is not directly used by _find_relevant_paths)
              path_and_validator = PathAndValidator(
                  dm_path=dm_path, validator=Validator(command="true $DMPATH"))

              # Define the expected relevant paths that each _find_relevant_paths_for_marker call will return
              relevant_paths_for_marker1: set[pathlib.Path] = {temp_path / "file_for_marker_one.py"}
              relevant_paths_for_marker2: set[pathlib.Path] = {temp_path / "file_for_marker_two_A.py", temp_path / "file_for_marker_two_B.py"}
              # Corrected: provide a dummy file for marker3 so validation passes
              relevant_paths_for_marker3: set[pathlib.Path] = {temp_path / "file_for_marker_three.py"}

              # Create these dummy files so that `done_validate` in `_find_relevant_paths_for_marker` succeeds
              for p in relevant_paths_for_marker1.union(relevant_paths_for_marker2).union(relevant_paths_for_marker3):
                p.write_text("dummy content", encoding='utf-8')

              # Prepare scripted messages for each agent loop initiated by _find_relevant_paths_for_marker
              scripted_messages = {
                  f"find_relevant_paths_for_{marker1_name_str}": [
                      Message(
                          role="assistant",
                          content_sections=[
                              ContentSection(
                                  content="",
                                  command=CommandInput(
                                      command_name="done",
                                      args=VariableMap({
                                          relevant_paths_variable:
                                              VariableValueStr(",".join(str(p) for p in relevant_paths_for_marker1)),
                                      }),
                                  ))
                          ])
                  ],
                  f"find_relevant_paths_for_{marker2_name_str}": [
                      Message(
                          role="assistant",
                          content_sections=[
                              ContentSection(
                                  content="",
                                  command=CommandInput(
                                      command_name="done",
                                      args=VariableMap({
                                          relevant_paths_variable:
                                              VariableValueStr(",".join(str(p) for p in relevant_paths_for_marker2)),
                                      }),
                                  ))
                          ])
                  ],
                  f"find_relevant_paths_for_{marker3_name_str}": [
                      Message(
                          role="assistant",
                          content_sections=[
                              ContentSection(
                                  content="",
                                  command=CommandInput(
                                      command_name="done",
                                      args=VariableMap({
                                          relevant_paths_variable:
                                              VariableValueStr(",".join(str(p) for p in relevant_paths_for_marker3)),
                                      }),
                                  ))
                          ])
                  ],
              }

              # 2. Build the workflow
              workflow = await self.build_workflow(scripted_messages)

              # 3. Call the method under test
              actual_relevant_paths_output = await workflow._find_relevant_paths(dm_path)

              # Prepare MarkerName objects to be consistent with get_markers' output
              # (get_markers is called internally, no need to mock it)
              import code_specs
              from code_specs_workflow import MUSHROOM

              marker1_obj = code_specs.MarkerName(char=MUSHROOM, name=marker1_name_str)
              marker2_obj = code_specs.MarkerName(char=MUSHROOM, name=marker2_name_str)
              marker3_obj = code_specs.MarkerName(char=MUSHROOM, name=marker3_name_str)

              # 4. Assertions
              # Assert that the output dictionary contains one entry for each marker found in path
              self.assertEqual(len(actual_relevant_paths_output), 3)

              # Assert that the keys are the correct MarkerName objects
              self.assertIn(marker1_obj, actual_relevant_paths_output)
              self.assertIn(marker2_obj, actual_relevant_paths_output)
              self.assertIn(marker3_obj, actual_relevant_paths_output)

              # Assert that the values correspond to the outputs provided by scripted_messages
              self.assertEqual(actual_relevant_paths_output[marker1_obj], relevant_paths_for_marker1)
              self.assertEqual(actual_relevant_paths_output[marker2_obj], relevant_paths_for_marker2)
              self.assertEqual(actual_relevant_paths_output[marker3_obj], relevant_paths_for_marker3)

              # Also check that conversations were created for each marker
              all_conversations = self.conversation_factory.GetAll()
              conversation_names = {c.GetName() for c in all_conversations}
              self.assertIn(f"find_relevant_paths_for_{marker1_name_str}", conversation_names)
              self.assertIn(f"find_relevant_paths_for_{marker2_name_str}", conversation_names)
              self.assertIn(f"find_relevant_paths_for_{marker3_name_str}", conversation_names)
    # ✨

  async def test_codespecsworkflow__find_relevant_paths_the_output_values_correspond_to_the_outputs_of__find_relevant_paths_for_marker_for_each_key_marker_1(
      self) -> None:
    # ✨ The output values correspond to the outputs of `_find_relevant_paths_for_marker` for each key (marker). (in CodeSpecsWorkflow._find_relevant_paths)
    # The `unittest` and `mock` imports are assumed to be at the file level.
    # `asyncio` is also assumed to be imported at the file level.
    # `collections.OrderedDict` can be imported within the test if not available globally.
    # `code_specs` and `code_specs_workflow.MUSHROOM` are already imported at the file level.
    # Adding explicit imports for `code_specs` and `MUSHROOM` to satisfy the "self-contained" constraint.
    import collections # For OrderedDict, if not globally available in the test environment.
    import code_specs
    from code_specs_workflow import MUSHROOM


    with tempfile.TemporaryDirectory() as temp_dir:
      temp_path = pathlib.Path(temp_dir)

      # 1. Setup: Create a dummy DM file with multiple unique markers
      dm_file_name = "output_values_test.dm.py"
      dm_path = temp_path / dm_file_name

      marker1_name_str = "ValueMarkerOne"
      marker2_name_str = "ValueMarkerTwo"
      marker3_name_str = "ValueMarkerThree"

      # Construct content for the DM file. Using string concatenation and chr(0x1F344)
      # to represent the mushroom character, consistent with other passing tests
      # and to avoid literal 🍄 in the test source code. Also ensuring that
      # the `{{` and `}}` are correctly part of the string literal without
      # causing f-string parsing issues.
      content = ("# DM file for output values test\n" +
                 "# {{" + chr(0x1F344) + " " + marker1_name_str + "}}\n" +
                 "# Code related to ValueMarkerOne\n" +
                 "# {{" + chr(0x1F344) + " " + marker2_name_str + "}}\n" +
                 "# Code related to ValueMarkerTwo\n" +
                 "# {{" + chr(0x1F344) + " " + marker3_name_str + "}}\n" +
                 "# Code related to ValueMarkerThree\n")
      dm_path.write_text(content, encoding='utf-8')

      # Create a PathAndValidator instance (validator is not directly used by _find_relevant_paths)
      path_and_validator = PathAndValidator(
          dm_path=dm_path, validator=Validator(command="true $DMPATH"))

      # Define the expected relevant paths that each _find_relevant_paths_for_marker call will return
      expected_relevant_paths_for_marker1: set[pathlib.Path] = {temp_path / "val_file_one.py", temp_path / "val_file_one_alt.py"}
      expected_relevant_paths_for_marker2: set[pathlib.Path] = {temp_path / "val_file_two.cc"}
      expected_relevant_paths_for_marker3: set[pathlib.Path] = {temp_path / "val_file_three.js", temp_path / "val_file_three_src.js"}

      # Create dummy files so that `done_validate` in `_find_relevant_paths_for_marker` succeeds
      for p in expected_relevant_paths_for_marker1.union(expected_relevant_paths_for_marker2).union(expected_relevant_paths_for_marker3):
        p.write_text("dummy content", encoding='utf-8')

      # Prepare scripted messages for each agent loop initiated by _find_relevant_paths_for_marker
      scripted_messages = {
          f"find_relevant_paths_for_{marker1_name_str}": [
              Message(
                  role="assistant",
                  content_sections=[
                      ContentSection(
                          content="",
                          command=CommandInput(
                              command_name="done",
                              args=VariableMap({
                                  relevant_paths_variable:
                                      VariableValueStr(','.join(str(p) for p in expected_relevant_paths_for_marker1)),
                              }),
                          ))
                  ])
          ],
          f"find_relevant_paths_for_{marker2_name_str}": [
              Message(
                  role="assistant",
                  content_sections=[
                      ContentSection(
                          content="",
                          command=CommandInput(
                              command_name="done",
                              args=VariableMap({
                                  relevant_paths_variable:
                                      VariableValueStr(','.join(str(p) for p in expected_relevant_paths_for_marker2)),
                              }),
                          ))
                  ])
          ],
          f"find_relevant_paths_for_{marker3_name_str}": [
              Message(
                  role="assistant",
                  content_sections=[
                      ContentSection(
                          content="",
                          command=CommandInput(
                              command_name="done",
                              args=VariableMap({
                                  relevant_paths_variable:
                                      VariableValueStr(','.join(str(p) for p in expected_relevant_paths_for_marker3)),
                              }),
                          ))
                  ])
          ],
      }

      # 2. Build the workflow with the correct scripted messages.
      workflow = await self.build_workflow(scripted_messages)

      # 3. Call the method under test
      actual_relevant_paths_output = await workflow._find_relevant_paths(dm_path)

      # 4. Assertions
      # The `get_markers` call inside `_find_relevant_paths` will use the actual file content.
      # The keys in the output will be `MarkerName` objects created by `get_markers`. 
      # Type annotation for `expected_marker_names_in_order`
      expected_marker_names_in_order: collections.OrderedDict[code_specs.MarkerName, None] = collections.OrderedDict()
      # Order of markers from get_markers is insertion order of first appearance.
      expected_marker_names_in_order[code_specs.MarkerName(char=MUSHROOM, name=marker1_name_str)] = None
      expected_marker_names_in_order[code_specs.MarkerName(char=MUSHROOM, name=marker2_name_str)] = None
      expected_marker_names_in_order[code_specs.MarkerName(char=MUSHROOM, name=marker3_name_str)] = None

      # Assert that the output dictionary contains one entry for each marker
      self.assertEqual(len(actual_relevant_paths_output), 3)

      # Assert that the keys are the correct MarkerName objects and in order
      self.assertEqual(list(actual_relevant_paths_output.keys()), list(expected_marker_names_in_order.keys()))

      # Assert that the values correspond to the outputs provided by scripted_messages
      self.assertEqual(actual_relevant_paths_output[code_specs.MarkerName(char=MUSHROOM, name=marker1_name_str)], expected_relevant_paths_for_marker1)
      self.assertEqual(actual_relevant_paths_output[code_specs.MarkerName(char=MUSHROOM, name=marker2_name_str)], expected_relevant_paths_for_marker2)
      self.assertEqual(actual_relevant_paths_output[code_specs.MarkerName(char=MUSHROOM, name=marker3_name_str)], expected_relevant_paths_for_marker3)
    # ✨

  async def test_codespecsworkflow__find_relevant_paths_for_marker_the_only_done_command_argument_given_to_prepare_command_registry_is_relevant_paths_variable_1(
      self) -> None:
    # ✨ The only done command argument given to `prepare_command_registry` is `relevant_paths_variable`. (in CodeSpecsWorkflow._find_relevant_paths_for_marker)
        with tempfile.TemporaryDirectory() as temp_dir:
          temp_path = pathlib.Path(temp_dir)

          # 1. Setup: Create a dummy DM file with a single marker
          dm_file_name = "single_marker.dm.py"
          dm_path = temp_path / dm_file_name

          marker_name_str = "RelevantPathsTest"
          # Use chr(0x1F344) to represent '🍄' to avoid literal character in the test source.
          mushroom_char = chr(0x1F344)

          # Construct the literal marker string for the DM file.
          literal_marker_in_file = (
              "# "  # Comment prefix
              + "{{"  # Start of Duende marker (literal string)
              + mushroom_char # The mushroom character (generated from chr())
              + " "  # Space after the mushroom character
              + marker_name_str # The marker name string
              + "}}"  # End of Duende marker (literal string)
          )

          # Construct the content string for the DM file using simple string concatenation
          content = (
              "# DM file for relevant paths argument test\n"
              + literal_marker_in_file + "\n"
              + "def dummy_func():\n"
              + "  pass\n"
          )
          dm_path.write_text(content, encoding='utf-8')

          # Create the expected MarkerName object
          import code_specs
          from code_specs_workflow import MUSHROOM
          marker_obj = code_specs.MarkerName(char=MUSHROOM, name=marker_name_str)

          # Create a dummy relevant file for the done_validator to pass
          dummy_relevant_file = temp_path / "dummy_relevant.py"
          dummy_relevant_file.write_text("print('hello')", encoding='utf-8')
          dummy_relevant_path_str = str(dummy_relevant_file)

          # 2. Prepare scripted messages for the FakeConversationalAI
          # The AI will call 'done' with the relevant_paths_variable
          conversation_name_for_marker = f"find_relevant_paths_for_{marker_name_str}"
          scripted_messages = {
              conversation_name_for_marker: [
                  Message(
                      role="assistant",
                      content_sections=[
                          ContentSection(
                              content="",
                              command=CommandInput(
                                  command_name="done",
                                  args=VariableMap({
                                      relevant_paths_variable:
                                          VariableValueStr(dummy_relevant_path_str),
                                  }),
                              ))
                      ]
                  )
              ]
          }

          # 3. Build the workflow
          workflow = await self.build_workflow(scripted_messages)

          # 4. Call the method under test
          # This call will internally execute an agent loop, and during that,
          # prepare_command_registry will be called to set up the 'done' command.
          returned_relevant_paths = await workflow._find_relevant_paths_for_marker(
              dm_path, marker_obj)

          # 5. Retrieve the conversation and inspect its command_registry
          conversation = None
          for conv in self.conversation_factory.GetAll():
            if conv.GetName() == conversation_name_for_marker:
              conversation = conv
              break
          self.assertIsNotNone(conversation,
                               f"Conversation '{conversation_name_for_marker}' not found.")
          assert conversation is not None # For mypy narrowing

          # Retrieve the DoneCommand using its public name
          done_command = conversation.command_registry.Get("done")

          # Assert that it's not None and is a DoneCommand instance
          self.assertIsNotNone(done_command, "'done' command not found in registry.")
          self.assertIsInstance(done_command, DoneCommand,
                                "Retrieved command is not a DoneCommand instance.")
          # Further narrow the type for mypy
          assert isinstance(done_command, DoneCommand), "done_command is not a DoneCommand instance after assertions."

          # 6. Assertions on the done command's arguments
          done_args = done_command.Syntax().arguments

          self.assertEqual(len(done_args), 1,
                           "Expected exactly one done command argument.")

          done_arg = done_args[0]
          self.assertIsInstance(done_arg, Argument)
          self.assertEqual(done_arg.name, relevant_paths_variable,
                           "The done command argument name should be relevant_paths_variable.")
          self.assertEqual(done_arg.arg_type, ArgumentContentType.PATH_UNVALIDATED,
                           "The done command argument type should be PATH_UNVALIDATED.")

          expected_description = ("Comma-separated list of local file paths that are relevant "
                                  "to implement the DM marker. "
                                  "Example: 'src/foo.py,src/bar.cc'.")
          self.assertEqual(done_arg.description, expected_description,
                           "The done command argument description is incorrect.")

          # Assert on the returned value from _find_relevant_paths_for_marker
          self.assertEqual(returned_relevant_paths, {dummy_relevant_file})
    # ✨

  async def test_codespecsworkflow__find_relevant_paths_for_marker_enables_caching_of_conversations_if_two_separate_instances_of_codespecsworkflow_have_this_method_called_with_the_same_inputs_the_2nd_call_reuses_the_outputs_from_the_first_1(
      self) -> None:
    # ✨ Enables caching of conversations: if two separate instances of CodeSpecsWorkflow have this method called with the same inputs, the 2nd call reuses the outputs from the first. (in CodeSpecsWorkflow._find_relevant_paths_for_marker)
    import output_cache # Import output_cache to refer to CachingDelegatingAgentLoopFactory
    from conversation_state import ConversationState # Import ConversationState

    with tempfile.TemporaryDirectory() as temp_dir:
      temp_path = pathlib.Path(temp_dir)

      # Create a single dm_path that both workflow instances will use
      dm_file_name = "cached_marker.dm.py"
      dm_path = temp_path / dm_file_name

      marker_name_str = "CacheTestMarker"
      mushroom_char = chr(0x1F344) # 🍄

      literal_marker_in_file = (
          "# " + "{{" + mushroom_char + " " + marker_name_str + "}}"
      )

      content = (
          "# DM file for caching test\n"
          + literal_marker_in_file + "\n"
          + "def cache_func():\n"
          + "  return 42\n"
      )
      dm_path.write_text(content, encoding='utf-8')

      import code_specs
      from code_specs_workflow import MUSHROOM
      marker_obj = code_specs.MarkerName(char=MUSHROOM, name=marker_name_str)

      dummy_relevant_file = temp_path / "dummy_cached_relevant.py"
      dummy_relevant_file.write_text("print('cached')", encoding='utf-8')
      dummy_relevant_path_str = str(dummy_relevant_file)
      expected_relevant_paths = {dummy_relevant_file}

      conversation_name_for_marker = f"find_relevant_paths_for_{marker_name_str}"
      scripted_messages = {
          conversation_name_for_marker: [
              Message(
                  role="assistant",
                  content_sections=[
                      ContentSection(
                          content="",
                          command=CommandInput(
                              command_name="done",
                              args=VariableMap({
                                  relevant_paths_variable:
                                      VariableValueStr(dummy_relevant_path_str),
                              }),
                          ))
                  ]
              )
          ]
      }

      # Create the first workflow instance
      workflow1 = await self.build_workflow(scripted_messages)

      print(f"[DEBUG] Before first call: All conversations: {[c.GetName() for c in self.conversation_factory.GetAll()]}")
      self.assertEqual(len([c for c in self.conversation_factory.GetAll() if c.GetName() == conversation_name_for_marker]), 0)

      # 4. First call to the method under test on workflow1
      # Print the cache key component to ensure consistency
      workflow_key_1 = f"code_specs_workflow:{dm_path}"
      print(f"[DEBUG] Workflow1 Cache Key Component: {workflow_key_1}")
      returned_relevant_paths_1 = await workflow1._find_relevant_paths_for_marker(
          dm_path, marker_obj)
      print(f"[DEBUG] Returned paths 1: {returned_relevant_paths_1}")

      # Verify after first call
      conversations_for_marker_1 = [c for c in self.conversation_factory.GetAll() if c.GetName() == conversation_name_for_marker]
      print(f"[DEBUG] After first call: Conversations for marker: {[c.GetName() + ' (' + str(c.GetState()) + ')' for c in conversations_for_marker_1]}")
      self.assertEqual(len(conversations_for_marker_1), 1, "Expected exactly one conversation after the first call.")
      self.assertEqual(conversations_for_marker_1[0].GetState(), ConversationState.DONE, "First conversation should be DONE.")
      self.assertEqual(returned_relevant_paths_1, expected_relevant_paths)

      # Create the second workflow instance (crucial for "two separate instances")
      workflow2 = await self.build_workflow(scripted_messages)

      # 5. Second call to the method under test with the exact same inputs, on workflow2
      # Print the cache key component to ensure consistency
      workflow_key_2 = f"code_specs_workflow:{dm_path}"
      print(f"[DEBUG] Workflow2 Cache Key Component: {workflow_key_2}")
      returned_relevant_paths_2 = await workflow2._find_relevant_paths_for_marker(
          dm_path, marker_obj)
      print(f"[DEBUG] Returned paths 2: {returned_relevant_paths_2}")

      # 6. Verification after second call
      all_conversations_after_second_call = self.conversation_factory.GetAll()
      conversations_for_marker_2 = [
          c for c in all_conversations_after_second_call
          if c.GetName() == conversation_name_for_marker
      ]
      print(f"[DEBUG] After second call: All conversations for marker: {[c.GetName() + ' (' + str(c.GetState()) + ')' for c in conversations_for_marker_2]}")

      # Assert that two conversations were created:
      # One from workflow1 (DONE), and one from workflow2 (DONE_FROM_CACHE).
      self.assertEqual(len(conversations_for_marker_2), 2, "Expected two conversations (one DONE, one DONE_FROM_CACHE).")

      done_count = 0
      done_from_cache_count = 0
      for conv in conversations_for_marker_2:
          if conv.GetState() == ConversationState.DONE:
              done_count += 1
          elif conv.GetState() == ConversationState.DONE_FROM_CACHE:
              done_from_cache_count += 1

      print(f"[DEBUG] Final counts: done_count={done_count}, done_from_cache_count={done_from_cache_count}")

      self.assertEqual(done_count, 1, "Expected one conversation with state DONE (from first run).")
      self.assertEqual(done_from_cache_count, 1, "Expected one conversation with state DONE_FROM_CACHE (from cached second run).")
      self.assertEqual(returned_relevant_paths_2, expected_relevant_paths)
    # ✨

  async def test_codespecsworkflow__find_relevant_paths_for_marker_done_validate_if_no_files_are_given_validation_fails_with_a_message_that_at_least_one_relevant_file_should_be_given_1(
      self) -> None:
    # ✨ If no files are given, validation fails, with a message that at least one relevant file should be given. (in CodeSpecsWorkflow._find_relevant_paths_for_marker.done_validate)
        import asyncio  # For async functions
        import code_specs
        from code_specs_workflow import MUSHROOM, relevant_paths_variable
        from agent_command import CommandInput, VariableMap, VariableName, VariableValueStr
        from message import ContentSection, Message
        from conversational_ai_test_utils import FakeConversationalAI
        from validation import ValidationResult

        with tempfile.TemporaryDirectory() as temp_dir:
          temp_path = pathlib.Path(temp_dir)

          # 1. Setup: Create a dummy DM file with a single marker
          dm_file_name = "no_files_given_validation_test.dm.py"
          dm_path = temp_path / dm_file_name

          marker_name_str = "NoFilesGiven"
          mushroom_char = chr(0x1F344)  # 🍄

          # Construct the literal marker string for the DM file.
          literal_marker_in_file = (
              "# "  # Comment prefix
              + "{{"  # Start of Duende marker (literal string)
              + mushroom_char # The mushroom character (generated from chr())
              + " "  # Space after the mushroom character
              + marker_name_str # The marker name string
              + "}}"  # End of Duende marker (literal string)
          )

          # Construct the content string for the DM file using simple string concatenation
          content = (
              "# DM file for 'no files given' validation test\n"
              + literal_marker_in_file + "\n"
              + "def test_func():\n"
              + "  pass\n"
          )
          dm_path.write_text(content, encoding='utf-8')

          # Create the expected MarkerName object
          marker_obj = code_specs.MarkerName(char=MUSHROOM, name=marker_name_str)

          # Create a dummy valid relevant file for the second 'done' call to succeed
          dummy_valid_file = temp_path / "valid_relevant.py"
          dummy_valid_file.write_text("import os\n", encoding='utf-8')
          dummy_valid_path_str = str(dummy_valid_file)

          # 2. Define the expected error message from done_validate
          # The error message should come from the 'if not relevant_paths_val:' block
          full_expected_error_message = (
              f"Error: '{relevant_paths_variable}' is missing. "
              "Please provide at least one relevant file path "
              "(e.g., 'src/foo.py,src/bar.cc').")

          # 3. Prepare scripted messages for the FakeConversationalAI
          conversation_name_for_marker = f"find_relevant_paths_for_{marker_name_str}"
          scripted_messages = {
              conversation_name_for_marker: [
                  # First attempt: Fails validation because relevant_paths is an empty string
                  Message(
                      role="assistant",
                      content_sections=[
                          ContentSection(
                              content="",
                              command=CommandInput(
                                  command_name="done",
                                  args=VariableMap({
                                      relevant_paths_variable: VariableValueStr(""),
                                  }),
                              ))
                      ]
                  ),
                  # Second attempt: Succeeds validation with a valid path
                  Message(
                      role="assistant",
                      content_sections=[
                          ContentSection(
                              content="",
                              command=CommandInput(
                                  command_name="done",
                                  args=VariableMap({
                                      relevant_paths_variable: VariableValueStr(dummy_valid_path_str),
                                  }),
                              ))
                      ]
                  ),
              ]
          }

          # 4. Build the workflow
          workflow = await self.build_workflow(scripted_messages)

          # 5. Call the method under test. This will run the agent loop.
          # It is expected to eventually succeed because of the second scripted message.
          returned_relevant_paths = await workflow._find_relevant_paths_for_marker(
              dm_path, marker_obj)

          # Assert that the method returned the paths from the successful attempt
          self.assertEqual(returned_relevant_paths, {dummy_valid_file})

          # 6. Retrieve the conversation and assert on the error message
          conversation = None
          for conv in self.conversation_factory.GetAll():
            if conv.GetName() == conversation_name_for_marker:
              conversation = conv
              break
          self.assertIsNotNone(conversation,
                               f"Conversation '{conversation_name_for_marker}' not found.")
          assert conversation is not None  # For mypy narrowing

          found_error_message_in_conversation = False
          for message in conversation.GetMessagesList():
            if message.role == "user":  # System errors are presented as user messages by FakeConversationalAI
              for section in message.GetContentSections():
                if section.content == full_expected_error_message:
                  found_error_message_in_conversation = True
                  break
              if found_error_message_in_conversation:
                break
          self.assertTrue(
              found_error_message_in_conversation,
              f"Expected error message '{full_expected_error_message}' not found in conversation history. "
              f"Actual content sections: {[s.content for m in conversation.GetMessagesList() for s in m.GetContentSections() if m.role == 'user']}."
          )
        # ✨

  async def test_codespecsworkflow__find_relevant_paths_for_marker_done_validate_all_files_must_be_readable_both_by_the_os_as_well_as_allowed_by_the_file_access_policy_if_one_isnt_validation_fails_1(
      self) -> None:

    # ✨ All files must be readable (both by the OS as well as allowed by the `file_access_policy`). If one isn't, validation fails. (in CodeSpecsWorkflow._find_relevant_paths_for_marker.done_validate)
        import asyncio  # For async functions
        import code_specs
        from code_specs_workflow import MUSHROOM, relevant_paths_variable
        from agent_command import CommandInput, VariableMap, VariableName, VariableValueStr
        from message import ContentSection, Message
        from conversational_ai_test_utils import FakeConversationalAI
        from validation import ValidationResult
        import os  # For os.chmod
        import stat  # For file permissions
        from file_access_policy import FileAccessPolicy # For the base class

        # Define a custom FakeFileAccessPolicy that can be controlled
        class ControlledFakeFileAccessPolicy(FileAccessPolicy):

            def __init__(self, denied_paths: set[pathlib.Path]):
                # Store resolved paths to handle symlinks, relative/absolute paths consistently
                self.denied_paths = {p.resolve() for p in denied_paths}

            def allow_access(self, path: str) -> bool:
                # Resolve the path being checked to compare with denied_paths
                normalized_path = pathlib.Path(path).resolve()
                return normalized_path not in self.denied_paths


        with tempfile.TemporaryDirectory() as temp_dir:
          temp_path = pathlib.Path(temp_dir)

          # 1. Setup: Create a dummy DM file with a single marker
          dm_file_name = "readable_validation_test.dm.py"
          dm_path = temp_path / dm_file_name

          marker_name_str = "ReadableFilesValidation"
          mushroom_char = chr(0x1F344)  # 🍄

          literal_marker_in_file = (
              "# " + "{{" + mushroom_char + " " + marker_name_str + "}}"
          )
          content = (
              "# DM file for readable files validation test\n"
              + literal_marker_in_file + "\n"
              + "def test_func():\n"
              + "  pass\n"
          )
          dm_path.write_text(content, encoding='utf-8')

          marker_obj = code_specs.MarkerName(char=MUSHROOM, name=marker_name_str)

          # --- Test Files Setup ---
          # 1. Non-existent file
          non_existent_file = temp_path / "non_existent.py"
          non_existent_path_str = str(non_existent_file)
          expected_error_non_existent = f"File '{non_existent_file}' does not exist."

          # 2. Path is a directory
          is_directory_path = temp_path / "a_directory"
          is_directory_path.mkdir()
          is_directory_path_str = str(is_directory_path)
          expected_error_is_directory = f"Path '{is_directory_path}' is not a file."

          # 3. File not readable by OS
          not_readable_os_file = temp_path / "not_readable_os.py"
          not_readable_os_file.write_text("private content", encoding='utf-8')
          # Remove all permissions to make it unreadable
          os.chmod(not_readable_os_file, 0o000)
          not_readable_os_path_str = str(not_readable_os_file)
          expected_error_not_readable_os = f"File '{not_readable_os_file}' is not readable by the OS."

          # 4. File access denied by policy
          denied_by_policy_file = temp_path / "denied_by_policy.py"
          denied_by_policy_file.write_text("secret content", encoding='utf-8')
          # Give it read permissions at OS level so policy is the only blocker
          os.chmod(denied_by_policy_file, stat.S_IRUSR)
          denied_by_policy_path_str = str(denied_by_policy_file)
          # Note: this file path will be added to the denied_paths of ControlledFakeFileAccessPolicy

          expected_error_denied_by_policy = f"Access to file '{denied_by_policy_file}' is not allowed by the file access policy."

          # 5. Valid readable file (for successful completion)
          valid_readable_file = temp_path / "valid_readable.py"
          valid_readable_file.write_text("public content", encoding='utf-8')
          os.chmod(valid_readable_file, stat.S_IRUSR | stat.S_IWUSR) # Read and write for owner
          valid_readable_path_str = str(valid_readable_file)

          # --- Prepare scripted messages ---
          conversation_name_for_marker = f"find_relevant_paths_for_{marker_name_str}"
          scripted_messages = {
              conversation_name_for_marker: [
                  # Attempt 1: Non-existent file
                  Message(
                      role="assistant",
                      content_sections=[
                          ContentSection(
                              content="",
                              command=CommandInput(
                                  command_name="done",
                                  args=VariableMap({
                                      relevant_paths_variable: VariableValueStr(non_existent_path_str),
                                  }),
                              ))
                      ]
                  ),
                  # Attempt 2: Path is a directory
                  Message(
                      role="assistant",
                      content_sections=[
                          ContentSection(
                              content="",
                              command=CommandInput(
                                  command_name="done",
                                  args=VariableMap({
                                      relevant_paths_variable: VariableValueStr(is_directory_path_str),
                                  }),
                              ))
                      ]
                  ),
                  # Attempt 3: File not readable by OS
                  Message(
                      role="assistant",
                      content_sections=[
                          ContentSection(
                              content="",
                              command=CommandInput(
                                  command_name="done",
                                  args=VariableMap({
                                      relevant_paths_variable: VariableValueStr(not_readable_os_path_str),
                                  }),
                              ))
                      ]
                  ),
                  # Attempt 4: File access denied by policy
                  Message(
                      role="assistant",
                      content_sections=[
                          ContentSection(
                              content="",
                              command=CommandInput(
                                  command_name="done",
                                  args=VariableMap({
                                      relevant_paths_variable: VariableValueStr(denied_by_policy_path_str),
                                  }),
                              ))
                      ]
                  ),
                  # Attempt 5: All files valid and readable (successful)
                  Message(
                      role="assistant",
                      content_sections=[
                          ContentSection(
                              content="",
                              command=CommandInput(
                                  command_name="done",
                                  args=VariableMap({
                                      relevant_paths_variable: VariableValueStr(valid_readable_path_str),
                                  }),
                              ))
                      ]
                  ),
              ]
          }

          # Override the file_access_policy for the workflow to use our controlled one
          # Resolve paths for consistency in ControlledFakeFileAccessPolicy
          denied_paths_set = {denied_by_policy_file.resolve()}
          controlled_file_access_policy = ControlledFakeFileAccessPolicy(denied_paths_set)

          # Build workflow with the original file access policy (it will be replaced)
          workflow = await self.build_workflow(scripted_messages)

          # Create new AgentLoopOptions with the controlled policy
          new_agent_loop_options = workflow._options.agent_loop_options._replace(file_access_policy=controlled_file_access_policy)

          # Update workflow._options with the new AgentLoopOptions
          workflow._options = workflow._options._replace(agent_loop_options=new_agent_loop_options)

          # Call the method under test. It is expected to eventually succeed due to the scripted messages.
          returned_relevant_paths = await workflow._find_relevant_paths_for_marker(
              dm_path, marker_obj)

          # Assert that the method returned the paths from the successful attempt
          self.assertEqual(returned_relevant_paths, {valid_readable_file})

          # Retrieve the conversation and assert on the error messages
          conversation = None
          for conv in self.conversation_factory.GetAll():
            if conv.GetName() == conversation_name_for_marker:
              conversation = conv
              break
          self.assertIsNotNone(conversation,
                               f"Conversation '{conversation_name_for_marker}' not found.")
          assert conversation is not None

          expected_error_messages = [
              f"Error: {expected_error_non_existent}",
              f"Error: {expected_error_is_directory}",
              f"Error: {expected_error_not_readable_os}",
              f"Error: {expected_error_denied_by_policy}",
          ]

          actual_error_messages = [
              section.content for message in conversation.GetMessagesList()
              if message.role == "user" and message.GetContentSections()
              for section in message.GetContentSections()
              if section.content.startswith("Error:")
          ]

          # Using assertListEqual to check both content and order of error messages
          self.assertListEqual(actual_error_messages, expected_error_messages,
                               "Mismatch in expected and actual error messages from validation failures.")

          # Revert file permissions for cleanup, if necessary (tempfile usually handles removal)
          # os.chmod(not_readable_os_file, stat.S_IRUSR | stat.S_IWUSR) # This is not strictly necessary as tempfile will clean up
    # ✨

  async def test_codespecsworkflow__find_relevant_paths_for_marker_done_validate_if_all_files_are_readable_both_by_the_os_and_file_access_policy_validation_succeeds_1(
      self) -> None:
    # ✨ If all files are readable (both by the OS and `file_access_policy`), validation succeeds. (in CodeSpecsWorkflow._find_relevant_paths_for_marker.done_validate)
        import asyncio  # For async functions
        import code_specs
        from code_specs_workflow import MUSHROOM, relevant_paths_variable
        from agent_command import CommandInput, VariableMap, VariableName, VariableValueStr
        from message import ContentSection, Message
        from conversational_ai_test_utils import FakeConversationalAI
        from validation import ValidationResult
        import os  # For os.chmod
        import stat  # For file permissions
        from conversation_state import ConversationState


        with tempfile.TemporaryDirectory() as temp_dir:
          temp_path = pathlib.Path(temp_dir)

          # 1. Setup: Create a dummy DM file with a single marker
          dm_file_name = "success_validation_test.dm.py"
          dm_path = temp_path / dm_file_name

          marker_name_str = "SuccessfulValidation"
          mushroom_char = chr(0x1F344)  # 🍄

          literal_marker_in_file = (
              "# " + "{{" + mushroom_char + " " + marker_name_str + "}}"
          )
          content = (
              "# DM file for successful validation test\n"
              + literal_marker_in_file + "\n"
              + "def test_func():\n"
              + "  pass\n"
          )
          dm_path.write_text(content, encoding='utf-8')

          marker_obj = code_specs.MarkerName(char=MUSHROOM, name=marker_name_str)

          # --- Test Files Setup ---
          # Create multiple valid readable files
          valid_file_1 = temp_path / "valid_file_1.py"
          valid_file_2 = temp_path / "valid_file_2.js"
          valid_file_3 = temp_path / "valid_file_3.txt"

          valid_file_1.write_text("print('hello from python')", encoding='utf-8')
          os.chmod(valid_file_1, stat.S_IRUSR | stat.S_IWUSR)

          valid_file_2.write_text("console.log('hello from js')", encoding='utf-8')
          os.chmod(valid_file_2, stat.S_IRUSR | stat.S_IWUSR)

          valid_file_3.write_text("hello from text file", encoding='utf-8')
          os.chmod(valid_file_3, stat.S_IRUSR | stat.S_IWUSR)

          expected_relevant_paths = {valid_file_1, valid_file_2, valid_file_3}
          valid_paths_str = ','.join(str(p) for p in expected_relevant_paths)

          # --- Prepare scripted messages ---
          conversation_name_for_marker = f"find_relevant_paths_for_{marker_name_str}"
          scripted_messages = {
              conversation_name_for_marker: [
                  Message(
                      role="assistant",
                      content_sections=[
                          ContentSection(
                              content="",
                              command=CommandInput(
                                  command_name="done",
                                  args=VariableMap({
                                      relevant_paths_variable: VariableValueStr(valid_paths_str),
                                  }),
                              ))
                      ]
                  )
              ]
          }

          # 4. Build the workflow (uses FakeFileAccessPolicy which allows all access)
          workflow = await self.build_workflow(scripted_messages)

          # 5. Call the method under test. It is expected to succeed.
          returned_relevant_paths = await workflow._find_relevant_paths_for_marker(
              dm_path, marker_obj)

          # 6. Assertions
          self.assertEqual(returned_relevant_paths, expected_relevant_paths,
                           "The returned relevant paths do not match the expected valid paths.")

          # Retrieve the conversation and assert its state
          conversation = None
          for conv in self.conversation_factory.GetAll():
            if conv.GetName() == conversation_name_for_marker:
              conversation = conv
              break
          self.assertIsNotNone(conversation,
                               f"Conversation '{conversation_name_for_marker}' not found.")
          assert conversation is not None  # For mypy narrowing

          self.assertEqual(conversation.GetState(), ConversationState.DONE,
                           "The conversation state should be DONE for successful validation.")

          # Verify that there were no 'Error:' messages in the conversation (indicating no validation failures)
          error_messages = [
              section.content for message in conversation.GetMessagesList()
              if message.role == "user" and message.GetContentSections()
              for section in message.GetContentSections()
              if section.content.startswith("Error:")
          ]
          self.assertEqual(len(error_messages), 0,
                           f"Expected no error messages in conversation, but found: {error_messages}")
    # ✨

  async def test_codespecsworkflow__implement_file_the_calls_to__implement_marker_happen_sequentially_1(
      self) -> None:
    pass  # {{🍄 The calls to `_implement_marker` happen sequentially. (in CodeSpecsWorkflow._implement_file)}}

  async def test_codespecsworkflow__implement_file_the_output_of_a_call_to__implement_marker_is_stored_through_markerimplementation_save_on_inputsoutput_path_1(
      self) -> None:
    pass  # {{🍄 The output of a call to `_implement_marker` is stored through `MarkerImplementation.save` on `inputs.output_path()`. (in CodeSpecsWorkflow._implement_file)}}

  async def test_codespecsworkflow__implement_file_the_output_of_a_call_to__implement_marker_is_stored_before_the_next_call_begins_so_that_the_next_call_already_sees_the_output_of_the_previous_call_1(
      self) -> None:
    pass  # {{🍄 The output of a call to `_implement_marker` is stored before the next call begins (so that the next call already sees the output of the previous call). (in CodeSpecsWorkflow._implement_file)}}

  async def test_codespecsworkflow__implement_file_the_calls_to__implement_marker_happen_in_the_order_in_which_the_markers_occur_in_the_dm_file_1(
      self) -> None:
    pass  # {{🍄 The calls to `_implement_marker` happen in the order in which the markers occur in the DM file. (in CodeSpecsWorkflow._implement_file)}}

  async def test_codespecsworkflow__implement_marker_for_each_file_in_relevant_paths_theres_a_section_in_the_initial_message_prompt_given_to_the_ai_1(
      self) -> None:
    pass  # {{🍄 For each file in `relevant_paths`, there's a section in the initial message (prompt) given to the AI. (in CodeSpecsWorkflow._implement_marker)}}

  async def test_codespecsworkflow__implement_marker_if_path_and_validatorold_path_exists_and_contains_an_implementation_for_marker_that_implementation_gets_included_as_the_last_section_of_the_initial_message_the_section_is_the_line_previous_implementation_followed_by_the_entire_implementation_of_the_marker_1(
      self) -> None:
    pass  # {{🍄 If `path_and_validator.old_path()` exists and contains an implementation for `marker`, that implementation gets included as the last section of the initial message. The section is the line "Previous implementation:", followed by the entire implementation (of the marker). (in CodeSpecsWorkflow._implement_marker)}}

  async def test_codespecsworkflow__implement_marker_the_only_done_command_argument_given_to_prepare_command_registry_is_implementation_variable_1(
      self) -> None:
    pass  # {{🍄 The only done command argument given to `prepare_command_registry` is `implementation_variable`. (in CodeSpecsWorkflow._implement_marker)}}

  async def test_codespecsworkflow__implement_marker_enables_caching_of_conversations_if_two_separate_instances_of_codespecsworkflow_have_this_method_called_for_the_same_path_and_validatordm_path_and_marker_the_2nd_call_reuses_the_outputs_from_the_first_1(
      self) -> None:
    pass  # {{🍄 Enables caching of conversations: if two separate instances of CodeSpecsWorkflow have this method called for the same `path_and_validator.dm_path` and marker, the 2nd call reuses the outputs from the first. (in CodeSpecsWorkflow._implement_marker)}}

  async def test_codespecsworkflow__implement_marker_doesnt_actually_overwrite_any_files_the_caller_does_1(
      self) -> None:
    pass  # {{🍄 Doesn't actually overwrite any files (the caller does). (in CodeSpecsWorkflow._implement_marker)}}


if __name__ == '__main__':
  unittest.main()