# DO NOT EDIT. This file is automatically generated by Duende.
# DM validator:
#
# mypy $DMPATH && $PYTHON -m pytest $DMPATH
#
# See src/test-constraints.md for constraints that apply to these tests.

import aiofiles
import asyncio
import pathlib
import tempfile
import unittest
from typing import Awaitable, Callable
from unittest import mock

from agent_command import Argument, ArgumentContentType, VariableMap, VariableName, VariableValueStr
from agent_loop_options import AgentLoopOptions, BaseAgentLoopFactory
from agent_workflow_options import AgentWorkflowOptions
from code_specs_agent import prepare_command_registry, prepare_initial_message, run_agent_loop
from command_registry import CommandRegistry
from conversation import ConversationFactory, ConversationFactoryOptions, Conversation
from conversational_ai_test_utils import FakeConversationalAIConversation, FakeConversationalAI
from done_command import DoneCommand, DoneValuesValidator
from file_access_policy import FileAccessPolicy
from list_files_command import ListFilesCommand
from message import ContentSection, Message
from read_file_command import ReadFileCommand
from search_file_command import SearchFileCommand
from selection_manager import SelectionManager
from test_utils import FakeFileAccessPolicy, FakeConfirmationState, FakeConfirmationManager, FakeSelectionManager
from validation import ValidationResult


class TestCodeSpecsAgent(unittest.IsolatedAsyncioTestCase):

  async def test_prepare_initial_message_relevant_files_read_asynchronously(
      self) -> None:
    # ✨ prepare_initial_message: `relevant_files` are read asynchronously.
    # The only exception is mocking parts of aiofiles in tests that need to
    # validate that operations are asynchronous.
    with tempfile.TemporaryDirectory() as temp_dir:
      temp_path = pathlib.Path(temp_dir)
      file1_path = temp_path / "file1.txt"
      file2_path = temp_path / "file2.txt"

      # Content that the mocked aiofiles.open will return
      file1_content = "Content of file 1."
      file2_content = "Content of file 2."

      relevant_files = {file1_path, file2_path}

      # Setup mocks for aiofiles.open to return specific content for each file
      mock_file_obj_1 = mock.AsyncMock()
      mock_file_obj_1.read.return_value = file1_content
      mock_context_manager_1 = mock.AsyncMock()
      mock_context_manager_1.__aenter__.return_value = mock_file_obj_1

      mock_file_obj_2 = mock.AsyncMock()
      mock_file_obj_2.read.return_value = file2_content
      mock_context_manager_2 = mock.AsyncMock()
      mock_context_manager_2.__aenter__.return_value = mock_file_obj_2

      # Map file paths to their respective mock context managers
      mock_context_managers = {
          file1_path: mock_context_manager_1,
          file2_path: mock_context_manager_2,
      }

      # Define the side_effect for aiofiles.open
      def aiofiles_open_side_effect(path, mode='r'):
        if path in mock_context_managers:
          return mock_context_managers[path]
        raise FileNotFoundError(
            f"Mocked aiofiles.open received unexpected path: {path}")

      # Patch aiofiles.open
      with mock.patch(
          'aiofiles.open',
          side_effect=aiofiles_open_side_effect) as mock_aiofiles_open:
        start_message_content = "This is the initial message."

        message = await prepare_initial_message(start_message_content,
                                                relevant_files)

        # Verify aiofiles.open was called for each file
        # Due to asynchronicity, order of calls might not be guaranteed, so use assert_any_call
        mock_aiofiles_open.assert_any_call(file1_path, mode='r')
        mock_aiofiles_open.assert_any_call(file2_path, mode='r')
        self.assertEqual(mock_aiofiles_open.call_count, 2)

        # Verify that the read method was awaited on each mock file object
        mock_file_obj_1.read.assert_awaited_once()
        mock_file_obj_2.read.assert_awaited_once()

        # --- Assert message content correctness (same as before) ---
        self.assertEqual(len(message.GetContentSections()), 3)
        self.assertEqual(message.GetContentSections()[0].content,
                         start_message_content)

        sorted_relevant_files = sorted(list(relevant_files))  # Already sorted

        expected_file_sections_sorted = []
        for file_path in sorted_relevant_files:
          # Use content directly from the mocked returns
          content_to_use = file1_content if file_path == file1_path else file2_content
          expected_file_sections_sorted.append(
              ContentSection(
                  content=f"File '{file_path}' follows:\n{content_to_use}"))

        self.assertEqual(message.GetContentSections()[1].content,
                         expected_file_sections_sorted[0].content)
        self.assertEqual(message.GetContentSections()[2].content,
                         expected_file_sections_sorted[1].content)
    # ✨

  async def test_prepare_initial_message_output_contains_start_message_content_as_first_section(
      self) -> None:
    # ✨ prepare_initial_message: The output contains `start_message_content` as its first section.
    with tempfile.TemporaryDirectory() as temp_dir:
      temp_path = pathlib.Path(temp_dir)
      file1_path = temp_path / "file1.txt"
      file2_path = temp_path / "file2.txt"

      file1_content = "Content of file 1."
      file2_content = "Content of file 2."

      async with aiofiles.open(file1_path, mode="w") as f:
        await f.write(file1_content)
      async with aiofiles.open(file2_path, mode="w") as f:
        await f.write(file2_content)

      start_message_content = "This is the initial message."
      relevant_files: set[pathlib.Path] = {file1_path, file2_path}

      message = await prepare_initial_message(start_message_content,
                                              relevant_files)

      self.assertEqual(message.GetContentSections()[0].content,
                       start_message_content)
      self.assertEqual(
          len(message.GetContentSections()), 1 + len(relevant_files))
    # ✨

  async def test_prepare_initial_message_if_relevant_files_empty_output_has_just_one_section(
      self) -> None:
    # ✨ prepare_initial_message: If `relevant_files` is empty, the output has just one section.
    start_message_content = "This is the initial message."
    relevant_files: set[pathlib.Path] = set()

    message = await prepare_initial_message(start_message_content,
                                            relevant_files)

    self.assertEqual(len(message.GetContentSections()), 1)
    self.assertEqual(message.GetContentSections()[0].content,
                     start_message_content)
    # ✨

  async def test_prepare_initial_message_if_relevant_file_cant_be_read_exception_bubbles_up(
      self) -> None:
    # ✨ prepare_initial_message: If a relevant file can't be read, raises an exception (or, rather, lets the underlying exception bubble up, doesn't catch it).
    with tempfile.TemporaryDirectory() as temp_dir:
      temp_path = pathlib.Path(temp_dir)
      non_existent_file_path = temp_path / "non_existent.txt"

      start_message_content = "This is the initial message."
      relevant_files = {non_existent_file_path}

      with self.assertRaises(FileNotFoundError):
        await prepare_initial_message(start_message_content, relevant_files)
    # ✨

  async def test_prepare_initial_message_content_section_for_each_relevant_file_with_path_and_contents(
      self) -> None:
    # ✨ prepare_initial_message: There is a content section in the start message given to the AgentLoop for each entry in `relevant_files`. It starts with a line "File '{path}' follows:" (with the corresponding path) and includes the entire contents of the file.
    with tempfile.TemporaryDirectory() as temp_dir:
      temp_path = pathlib.Path(temp_dir)
      file1_path = temp_path / "file1.txt"
      file2_path = temp_path / "file2.txt"

      file1_content = "Content of file 1."
      file2_content = "Content of file 2."

      async with aiofiles.open(file1_path, mode="w") as f:
        await f.write(file1_content)
      async with aiofiles.open(file2_path, mode="w") as f:
        await f.write(file2_content)

      start_message_content = "This is the initial message."
      relevant_files = {file1_path, file2_path}

      message = await prepare_initial_message(start_message_content,
                                              relevant_files)

      self.assertEqual(
          len(message.GetContentSections()), 1 + len(relevant_files))
      self.assertEqual(message.GetContentSections()[0].content,
                       start_message_content)

      # Files are sorted by path for consistent order
      sorted_relevant_files = sorted(list(relevant_files))

      expected_file_sections_sorted = []
      for file_path in sorted_relevant_files:
        content = ""
        if file_path == file1_path:
          content = file1_content
        elif file_path == file2_path:
          content = file2_content
        expected_file_sections_sorted.append(
            ContentSection(content=f"File '{file_path}' follows:\n{content}"))

      self.assertEqual(message.GetContentSections()[1].content,
                       expected_file_sections_sorted[0].content)
      self.assertEqual(message.GetContentSections()[2].content,
                       expected_file_sections_sorted[1].content)
    # ✨

  async def test_prepare_command_registry_has_expected_agent_commands(
      self) -> None:
    # ✨ prepare_command_registry: The command registry given has exactly these agent commands: ReadFileCommand(…), ListFilesCommand(…), SearchFileCommand(…), done_command
    async def dummy_validator(inputs: VariableMap) -> ValidationResult:
      return ValidationResult(True, "", "")

    file_access_policy = FakeFileAccessPolicy()
    done_command_arguments = [
        Argument(
            VariableName("output"),
            ArgumentContentType.STRING,
            "The output of the agent.",
        )
    ]

    registry = await prepare_command_registry(done_command_arguments,
                                              dummy_validator,
                                              file_access_policy)

    registered_commands = registry.GetCommands()

    # Verify that the registry contains exactly the expected types of commands.
    registered_command_types = {type(cmd) for cmd in registered_commands}
    expected_command_types = {
        type(ReadFileCommand(file_access_policy)),
        type(ListFilesCommand(file_access_policy)),
        type(SearchFileCommand(file_access_policy)),
        DoneCommand,
    }
    self.assertEqual(registered_command_types, expected_command_types)

    # Verify DoneCommand specifics
    done_command_from_registry = None
    for cmd in registered_commands:
      if isinstance(cmd, DoneCommand):
        done_command_from_registry = cmd
        break

    self.assertIsNotNone(done_command_from_registry)
    assert isinstance(done_command_from_registry, DoneCommand)

    self.assertEqual(done_command_from_registry._arguments,
                     done_command_arguments)
    self.assertIsInstance(done_command_from_registry._values_validator,
                          DoneValuesValidator)
    self.assertEqual(
        done_command_from_registry._values_validator._callback,  # type: ignore
        dummy_validator)
    # ✨

  async def test_run_agent_loop_returns_variable_map_from_done_command(
      self) -> None:
    # ✨ run_agent_loop: Returns the `VariableMap` with all the values given to `DoneCommand`.
    # Imports needed within the method for specific type references not at global scope.
    from agent_command import CommandInput, VariableValueInt
    from agent_loop import AgentLoopFactory  # Import the actual AgentLoopFactory

    # 1. Define the expected VariableMap that the DoneCommand would return.
    expected_done_variables = VariableMap({
        VariableName("result"): VariableValueStr("success"),
        VariableName("value"): VariableValueInt(123),
    })

    # 2. Setup a ConversationalAI that returns a message with the done command.
    done_command_input_for_ai_response = CommandInput(
        command_name="done", args=expected_done_variables)

    done_message_from_ai = Message(
        role="assistant",
        content_sections=[
            ContentSection(
                content="I have completed the task and am calling done.",
                command=done_command_input_for_ai_response)
        ])

    # The conversation name that run_agent_loop will use.
    conversation_name_for_test = "test_conversation"

    # Use FakeConversationalAI directly, providing scripted_responses as a dictionary with the conversation name as key.
    fake_conversational_ai = FakeConversationalAI(
        scripted_responses={conversation_name_for_test: [done_message_from_ai]})

    # 3. Setup CommandRegistry with a DoneCommand.
    class TestCallbackDoneValuesValidator(DoneValuesValidator):

      def __init__(self, callback: Callable[[VariableMap],
                                            Awaitable[ValidationResult]]):
        self._callback = callback

      async def validate(self, inputs: VariableMap) -> ValidationResult:
        return await self._callback(inputs)

    async def dummy_validator(inputs: VariableMap) -> ValidationResult:
      return ValidationResult(True, "", "")

    done_command_arguments = [
        Argument(
            VariableName("result"),
            ArgumentContentType.STRING,
            "The result of the agent.",
        ),
        Argument(
            VariableName("value"),
            ArgumentContentType.INTEGER,
            "A numeric value.",
        ),
    ]

    file_access_policy = FakeFileAccessPolicy()
    command_registry = await prepare_command_registry(done_command_arguments,
                                                      dummy_validator,
                                                      file_access_policy)

    # 4. Use the standard AgentLoopFactory.
    agent_loop_factory = AgentLoopFactory()

    # 5. Prepare other components for AgentLoopOptions and AgentWorkflowOptions.
    fake_confirmation_manager = FakeConfirmationManager()
    fake_confirmation_state = FakeConfirmationState(
        confirmation_manager=fake_confirmation_manager)

    start_message = await prepare_initial_message("Initial message", set())

    real_conversation_factory_options = ConversationFactoryOptions()
    conversation_factory = ConversationFactory(
        options=real_conversation_factory_options)

    selection_manager = FakeSelectionManager()

    # 6. Create AgentLoopOptions and AgentWorkflowOptions.
    # Use the consistent conversation name for dummy_conversation creation.
    dummy_conversation = conversation_factory.New(conversation_name_for_test,
                                                  command_registry)

    agent_loop_options = AgentLoopOptions(
        conversation=dummy_conversation,
        start_message=start_message,
        command_registry=command_registry,
        confirmation_state=fake_confirmation_state,
        file_access_policy=file_access_policy,
        conversational_ai=fake_conversational_ai,
    )

    workflow_options = AgentWorkflowOptions(
        agent_loop_options=agent_loop_options,
        agent_loop_factory=agent_loop_factory,
        conversation_factory=conversation_factory,
        selection_manager=selection_manager,
    )

    # Use the consistent conversation name for run_agent_loop.
    conversation_name_for_run = conversation_name_for_test

    # 7. Run the agent loop.
    actual_done_variables = await run_agent_loop(workflow_options,
                                                 conversation_name_for_run,
                                                 start_message,
                                                 command_registry)

    # 8. Assert that the returned VariableMap matches the expected one.
    self.assertEqual(actual_done_variables, expected_done_variables)
    # ✨

  async def test_run_agent_loop_conversation_has_given_name(self) -> None:
    # ✨ run_agent_loop: The conversation started has name `conversation_name`.
    from agent_loop import AgentLoopFactory
    from agent_loop_options import AgentLoopOptions
    from agent_workflow_options import AgentWorkflowOptions
    from conversation import Conversation, ConversationFactory, ConversationFactoryOptions
    from conversational_ai_test_utils import FakeConversationalAI
    from done_command import DoneValuesValidator
    from test_utils import FakeConfirmationManager, FakeConfirmationState, FakeFileAccessPolicy, FakeSelectionManager
    from validation import ValidationResult, CreateValidationManager
    from typing import Awaitable, Callable, List, Tuple
    from agent_command import Argument, VariableMap, CommandInput, VariableName, VariableValueStr, ArgumentContentType
    from command_registry import CommandRegistry
    from message import ContentSection, Message

    # Spy class for ConversationFactory to record calls to its `New` method.
    # This is used instead of unittest.mock to adhere to the test constraints
    # that "Mock is NOT allowed in this code" for dependencies of code_specs_agent.
    class SpyConversationFactory(ConversationFactory):

      def __init__(self, options: ConversationFactoryOptions):
        super().__init__(options)
        self.new_calls: List[Tuple[str, CommandRegistry]] = []

      def New(self, conversation_name: str,
              command_registry: CommandRegistry) -> Conversation:
        self.new_calls.append((conversation_name, command_registry))
        # Delegate to the real ConversationFactory.New to return a valid Conversation object
        # which is required for the AgentLoop to run without errors.
        return super().New(conversation_name, command_registry)

    # Define minimal fakes for unprovided dependencies, using real implementations
    # or the fakes provided by test_utils and conversational_ai_test_utils.
    test_conversation_name = "test_conversation_name_123"

    # Define a done command response for the fake conversational AI
    done_command_input_for_ai_response = CommandInput(
        command_name="done",
        args=VariableMap(
            {VariableName("output"): VariableValueStr("Test completed")}))
    done_message_from_ai = Message(
        role="assistant",
        content_sections=[
            ContentSection(
                content="Task finished.",
                command=done_command_input_for_ai_response)
        ])
    fake_conversational_ai = FakeConversationalAI(
        scripted_responses={test_conversation_name: [done_message_from_ai]})

    fake_confirmation_manager = FakeConfirmationManager()
    fake_confirmation_state = FakeConfirmationState(
        confirmation_manager=fake_confirmation_manager)
    file_access_policy = FakeFileAccessPolicy()
    selection_manager = FakeSelectionManager()
    validation_manager = CreateValidationManager()

    # Prepare command registry with a dummy validator and no specific arguments
    # as the done command's behavior is not under test here.
    async def dummy_validator(inputs: VariableMap) -> ValidationResult:
      return ValidationResult(True, "", "")

    done_command_arguments: List[Argument] = [
        Argument(
            VariableName("output"),
            ArgumentContentType.STRING,
            "The output of the agent.",
        )
    ]
    command_registry = await prepare_command_registry(done_command_arguments,
                                                      dummy_validator,
                                                      file_access_policy)

    # Prepare start message
    start_message = await prepare_initial_message("Initial message", set())

    # Create the real AgentLoopFactory
    agent_loop_factory = AgentLoopFactory()

    # Create an instance of the SpyConversationFactory.
    # This factory will be passed to AgentWorkflowOptions.
    real_conversation_factory_options = ConversationFactoryOptions()
    spy_conversation_factory = SpyConversationFactory(
        real_conversation_factory_options)

    # Create a dummy Conversation object for the initial AgentLoopOptions.
    # This is a placeholder because run_agent_loop will replace it with the
    # conversation created by the `conversation_factory.New` call.
    dummy_conversation_for_options = Conversation(
        name="dummy_name_for_options",
        unique_id=123,
        command_registry=command_registry,
    )

    agent_loop_options = AgentLoopOptions(
        conversation=dummy_conversation_for_options,
        start_message=start_message,
        command_registry=command_registry,
        confirmation_state=fake_confirmation_state,
        file_access_policy=file_access_policy,
        conversational_ai=fake_conversational_ai,
        validation_manager=validation_manager,
    )

    workflow_options = AgentWorkflowOptions(
        agent_loop_options=agent_loop_options,
        agent_loop_factory=agent_loop_factory,
        conversation_factory=spy_conversation_factory,
        selection_manager=selection_manager)

    # Run the agent loop.
    # The `run_agent_loop` function internally calls `workflow_options.conversation_factory.New`.
    await run_agent_loop(workflow_options, test_conversation_name,
                         start_message, command_registry)

    # Assert that SpyConversationFactory.New was called exactly once
    # with the correct conversation_name and command_registry.
    self.assertEqual(len(spy_conversation_factory.new_calls), 1)
    called_conversation_name, called_command_registry = spy_conversation_factory.new_calls[
        0]
    self.assertEqual(called_conversation_name, test_conversation_name)
    self.assertEqual(called_command_registry, command_registry)
    # ✨

  async def test_run_agent_loop_start_message_is_initial_message(self) -> None:
    # ✨ run_agent_loop: `start_message` is given as the initial message.
    from agent_loop import AgentLoopFactory
    from agent_loop_options import AgentLoopOptions
    from agent_workflow_options import AgentWorkflowOptions
    from conversation import Conversation, ConversationFactory, ConversationFactoryOptions
    from conversational_ai_test_utils import FakeConversationalAI
    from done_command import DoneValuesValidator
    from test_utils import FakeConfirmationManager, FakeConfirmationState, FakeFileAccessPolicy, FakeSelectionManager
    from validation import ValidationResult, CreateValidationManager
    from typing import Awaitable, Callable, List, Optional
    from agent_command import Argument, VariableMap, CommandInput, VariableName, VariableValueStr, ArgumentContentType
    from command_registry import CommandRegistry
    from message import ContentSection, Message

    # Define minimal fakes for unprovided dependencies.
    test_conversation_name = "test_conversation_for_start_message_v4"  # Renamed for uniqueness

    # Define a done command response for the fake conversational AI to terminate the loop.
    done_command_input_for_ai_response = CommandInput(
        command_name="done",
        args=VariableMap({
            VariableName("output"):
                VariableValueStr("Test completed for start message v4")
        }))
    done_message_from_ai = Message(
        role="assistant",
        content_sections=[
            ContentSection(
                content="Task finished for start message v4.",
                command=done_command_input_for_ai_response)
        ])
    fake_conversational_ai = FakeConversationalAI(
        scripted_responses={test_conversation_name: [done_message_from_ai]})

    fake_confirmation_manager = FakeConfirmationManager()
    fake_confirmation_state = FakeConfirmationState(
        confirmation_manager=fake_confirmation_manager)
    file_access_policy = FakeFileAccessPolicy()
    selection_manager = FakeSelectionManager()
    validation_manager = CreateValidationManager()

    # Prepare command registry with a dummy validator.
    async def dummy_validator(inputs: VariableMap) -> ValidationResult:
      return ValidationResult(True, "", "")

    done_command_arguments: List[Argument] = [
        Argument(
            VariableName("output"),
            ArgumentContentType.STRING,
            "The output of the agent.",
        )
    ]
    command_registry = await prepare_command_registry(done_command_arguments,
                                                      dummy_validator,
                                                      file_access_policy)

    # Prepare the specific start_message we want to test.
    expected_start_message = await prepare_initial_message(
        "Expected initial message content v4.", set())

    # Create a real ConversationFactory.
    real_conversation_factory_options = ConversationFactoryOptions()
    conversation_factory = ConversationFactory(
        real_conversation_factory_options)

    # Create a real AgentLoopFactory.
    agent_loop_factory = AgentLoopFactory()

    # Create a dummy Conversation object for the initial AgentLoopOptions.
    # This will be replaced by the conversation created by run_agent_loop.
    dummy_conversation_for_options = Conversation(
        name="dummy_name_for_start_message_options_v4",
        unique_id=1213,  # Unique ID
        command_registry=command_registry,
    )

    agent_loop_options = AgentLoopOptions(
        conversation=dummy_conversation_for_options,
        start_message=Message(
            role="user",
            content_sections=[
                ContentSection(content="This placeholder will be replaced")
            ]),  # This placeholder will be replaced by run_agent_loop
        command_registry=command_registry,
        confirmation_state=fake_confirmation_state,
        file_access_policy=file_access_policy,
        conversational_ai=fake_conversational_ai,
        validation_manager=validation_manager,
    )

    workflow_options = AgentWorkflowOptions(
        agent_loop_options=agent_loop_options,
        agent_loop_factory=agent_loop_factory,
        conversation_factory=conversation_factory,  # Use the real factory
        selection_manager=selection_manager)

    # Run the agent loop.
    await run_agent_loop(workflow_options, test_conversation_name,
                         expected_start_message, command_registry)

    # Retrieve the conversation from the conversation_factory by iterating through all of them
    # and finding the one with the matching name.
    found_conversation: Optional[Conversation] = None
    for conv in conversation_factory.GetAll():
      if conv.name() == test_conversation_name:
        found_conversation = conv
        break

    self.assertIsNotNone(
        found_conversation,
        f"Conversation with name '{test_conversation_name}' was not found.")

    # Cast to assure mypy that it's not None after the assert.
    actual_conversation: Conversation = found_conversation  # type: ignore

    # Assert that the first message in the conversation is our expected_start_message.
    # The AgentLoop adds the start_message as the first message to the conversation.
    messages = actual_conversation.GetMessagesList()
    self.assertGreater(len(messages), 0, "Conversation should not be empty.")
    self.assertEqual(messages[0].role, expected_start_message.role)
    self.assertEqual(messages[0].GetContentSections(),
                     expected_start_message.GetContentSections())
    # ✨


if __name__ == '__main__':
  unittest.main()
