# DO NOT EDIT. This file is automatically generated by Duende.
from dataclasses import dataclass
import logging
import pathlib

from agent_command import AgentCommand, CommandOutput, CommandSyntax, Argument, ArgumentContentType, PATH_VARIABLE_NAME, REASON_VARIABLE, VariableMap, VariableName
from file_access_policy import FileAccessPolicy


@dataclass
class PathBox:
  path: pathlib.Path


class ChangeWorkingDirectoryCommand(AgentCommand):

  def __init__(self, working_directory: PathBox) -> None:
    # ✨ init method
    self._working_directory = working_directory
    # ✨

  def Name(self) -> str:
    return self.Syntax().name

  @classmethod
  def Syntax(cls) -> CommandSyntax:
    return CommandSyntax(
        name="chdir",
        description="Changes the current working directory (affecting agent commands).",
        arguments=[
            REASON_VARIABLE,
            Argument(
                name=PATH_VARIABLE_NAME,
                arg_type=ArgumentContentType.PATH_INPUT,
                description="New working directory.",
                required=False)
        ])

  async def run(self, inputs: VariableMap) -> CommandOutput:
    """Assigns input `path` to `self._working_directory`."""
    # ✨ run method
    path_input = inputs[PATH_VARIABLE_NAME]
    assert isinstance(path_input, pathlib.Path)
    path_input = self._working_directory.path / path_input
    if not path_input.exists():
      return CommandOutput(
          command_name=self.Name(),
          output="",
          errors=f"Path '{path_input}' does not exist.",
          summary=f"Failed to change directory to '{path_input}'. Path does not exist.",
      )

    if not path_input.is_dir():
      return CommandOutput(
          command_name=self.Name(),
          output="",
          errors=f"Path '{path_input}' is not a directory.",
          summary=f"Failed to change directory to '{path_input}'. Path is not a directory.",
      )

    self._working_directory.path = path_input.resolve()
    return CommandOutput(
        command_name=self.Name(),
        output=f"Working directory changed to: {self._working_directory.path}",
        errors="",
        summary=f"Working directory changed to '{self._working_directory.path}'.",
    )
    # ✨
